# Shared strings for the content-first quest layer. Columns: en, es, pt, fr, de, ja, ko, zh
COMMON = {
    # --- Objective templates (%s = translated name) ---------------------------------------------
    "QO_T_TALK": ["Talk to %s", "Habla con %s", "Fale com %s", "Parler à %s", "Sprich mit %s", "%sと話す", "%s와(과) 대화", "与%s交谈"],
    "QO_T_RETURN": ["Return to %s", "Vuelve con %s", "Volte a %s", "Retourner voir %s", "Kehre zu %s zurück", "%sのもとへ戻る", "%s에게 돌아가기", "回到%s身边"],
    "QO_T_GIVE": ["Bring %s to %s", "Lleva %s a %s", "Leve %s a %s", "Apporter %s à %s", "Bring %s zu %s", "%sを%sに届ける", "%s을(를) %s에게 전달", "把%s交给%s"],
    "QO_T_DEFEAT": ["Defeat %s", "Derrota a %s", "Derrote %s", "Vaincre %s", "Besiege %s", "%sを倒す", "%s 처치", "击败%s"],
    "QO_T_HUNT": ["Hunt %s", "Caza %s", "Cace %s", "Chasser %s", "Jage %s", "%sを狩る", "%s 사냥", "狩猎%s"],
    "QO_T_CLEAR": ["Drive off %s", "Ahuyenta a %s", "Afaste %s", "Chasser %s du lieu", "Vertreibe %s", "%sを追い払う", "%s 몰아내기", "驱逐%s"],
    "QO_T_FIND": ["Find %s", "Encuentra %s", "Encontre %s", "Trouver %s", "Finde %s", "%sを見つける", "%s 찾기", "找到%s"],
    "QO_T_REACH": ["Reach %s", "Llega a %s", "Chegue a %s", "Atteindre %s", "Erreiche %s", "%sへ向かう", "%s에 도달", "抵达%s"],
    "QO_T_CLIMB": ["Climb %s", "Escala %s", "Escale %s", "Escalader %s", "Erklimme %s", "%sを登る", "%s 오르기", "攀上%s"],
    "QO_T_GLIDE": ["Glide to %s", "Planea hasta %s", "Plane até %s", "Planer jusqu'à %s", "Gleite zu %s", "%sまで滑空する", "%s까지 활공", "滑翔至%s"],
    "QO_T_SWIM": ["Swim to %s", "Nada hasta %s", "Nade até %s", "Nager jusqu'à %s", "Schwimm zu %s", "%sまで泳ぐ", "%s까지 수영", "游到%s"],
    "QO_T_COLLECT": ["Collect %s", "Reúne %s", "Reúna %s", "Réunir %s", "Sammle %s", "%sを集める", "%s 모으기", "收集%s"],
    "QO_T_GATHER": ["Gather from %s", "Recolecta de %s", "Colha de %s", "Récolter sur %s", "Ernte von %s", "%sから採る", "%s에서 채집", "从%s采集"],
    "QO_T_COOK": ["Cook %s", "Cocina %s", "Cozinhe %s", "Cuisiner %s", "Koche %s", "%sを作る", "%s 요리", "烹饪%s"],
    "QO_T_CRAFT": ["Craft %s", "Fabrica %s", "Fabrique %s", "Fabriquer %s", "Fertige %s", "%sを作る", "%s 제작", "制作%s"],
    "QO_T_EXAMINE": ["Examine %s", "Examina %s", "Examine %s", "Examiner %s", "Untersuche %s", "%sを調べる", "%s 조사", "调查%s"],
    "QO_T_TAKE": ["Take %s", "Toma %s", "Pegue %s", "Prendre %s", "Nimm %s", "%sを手に入れる", "%s 챙기기", "拿到%s"],
    "QO_T_FREE": ["Free %s", "Libera a %s", "Liberte %s", "Libérer %s", "Befreie %s", "%sを助け出す", "%s 구출", "救出%s"],
    "QO_T_PROTECT": ["Protect %s", "Protege a %s", "Proteja %s", "Protéger %s", "Beschütze %s", "%sを守る", "%s 보호", "保护%s"],
    "QO_T_ESCORT": ["Escort %s", "Escolta a %s", "Escolte %s", "Escorter %s", "Geleite %s", "%sを護衛する", "%s 호위", "护送%s"],
    "QO_T_SURVIVE": ["Hold out at %s", "Resiste en %s", "Resista em %s", "Tenir bon à %s", "Halte aus: %s", "%sで持ちこたえる", "%s에서 버티기", "在%s坚守"],
    "QO_T_DESTROY": ["Destroy %s", "Destruye %s", "Destrua %s", "Détruire %s", "Zerstöre %s", "%sを壊す", "%s 파괴", "摧毁%s"],
    "QO_T_LIGHT": ["Light %s", "Enciende %s", "Acenda %s", "Allumer %s", "Entzünde %s", "%sに火を灯す", "%s 밝히기", "点亮%s"],
    "QO_T_RING": ["Ring %s", "Toca %s", "Toque %s", "Faire sonner %s", "Läute %s", "%sを鳴らす", "%s 울리기", "敲响%s"],
    "QO_T_SOLVE": ["Solve the seal of %s", "Resuelve el sello de %s", "Resolva o selo de %s", "Résoudre le sceau de %s", "Löse das Siegel von %s", "%sの封印を解く", "%s의 봉인 풀기", "解开%s的封印"],
    "QO_T_OPEN": ["Open %s", "Abre %s", "Abra %s", "Ouvrir %s", "Öffne %s", "%sを開ける", "%s 열기", "打开%s"],
    "QO_T_ENTER": ["Enter %s", "Entra en %s", "Entre em %s", "Entrer dans %s", "Betritt %s", "%sに入る", "%s에 들어가기", "进入%s"],
    "QO_T_COURSE": ["Finish %s", "Completa %s", "Complete %s", "Terminer %s", "Schaffe %s", "%sを完走する", "%s 완주", "完成%s"],
    "QO_T_COURSE_PAR": ["Finish %s in under %s s", "Completa %s en menos de %s s", "Complete %s em menos de %s s", "Terminer %s en moins de %s s", "Schaffe %s unter %s s", "%sを%s秒以内に完走", "%s를 %s초 안에 완주", "完成%s（%s秒内）"],
    "QO_T_SNEAK": ["Take down %s unseen", "Abate a %s sin ser visto", "Derrube %s sem ser visto", "Abattre %s sans être vu", "Erledige %s unbemerkt", "気づかれずに%sを倒す", "들키지 않고 %s 처치", "悄无声息地击倒%s"],
    "QO_T_USE": ["Use %s", "Usa %s", "Use %s", "Utiliser %s", "Nutze %s", "%sを使う", "%s 사용", "使用%s"],
    "QO_T_TAME": ["Tame %s", "Doma %s", "Dome %s", "Apprivoiser %s", "Zähme %s", "%sを手懐ける", "%s 길들이기", "驯服%s"],
    "QO_T_ALTAR": ["Offer jade at %s", "Ofrece jade en %s", "Ofereça jade em %s", "Offrir du jade à %s", "Opfere Jade bei %s", "%sで翡翠を捧げる", "%s에 비취 바치기", "在%s献上翡翠"],
    "QO_T_NIGHT": ["%s (at night)", "%s (de noche)", "%s (à noite)", "%s (la nuit)", "%s (nachts)", "%s（夜に）", "%s (밤에)", "%s（夜间）"],
    # --- Quest flow / journal ---------------------------------------------------------------------
    "QUEST_DISCOVERY": ["A discovery", "Un descubrimiento", "Uma descoberta", "Une découverte", "Eine Entdeckung", "発見", "발견", "新发现"],
    "QUEST_DISCOVERED": ["Something here: %s", "Algo aquí: %s", "Algo aqui: %s", "Quelque chose ici : %s", "Hier ist etwas: %s", "何かある：%s", "뭔가 있다: %s", "此处有异：%s"],
    "QUEST_STAGE_RETRY": ["Not this time. Try again.", "Esta vez no. Inténtalo de nuevo.", "Não desta vez. Tente de novo.", "Pas cette fois. Réessayez.", "Diesmal nicht. Versuch es erneut.", "今回は駄目だ。もう一度。", "이번엔 실패. 다시 해보자.", "这次不行，再来一次。"],
    "JOURNAL_MAIN": ["The Warden's Road", "El camino del Guardián", "O caminho do Guardião", "La voie du Gardien", "Der Weg des Hüters", "守り人の道", "지기의 길", "守风者之路"],
    "JOURNAL_SIDE": ["Tales", "Historias", "Histórias", "Récits", "Geschichten", "頼まれごと", "이야기", "故事"],
    "JOURNAL_DISCOVERIES": ["Discoveries", "Descubrimientos", "Descobertas", "Découvertes", "Entdeckungen", "発見", "발견", "发现"],
    "JOURNAL_BOUNTIES": ["Bounties & trials", "Recompensas y pruebas", "Recompensas e provas", "Primes et épreuves", "Kopfgelder & Prüfungen", "賞金首と試練", "현상금과 시련", "悬赏与试炼"],
    "JOURNAL_RUMORS": ["Rumours", "Rumores", "Rumores", "Rumeurs", "Gerüchte", "うわさ", "소문", "传闻"],
    "JOURNAL_RUMOR_AT": ["%s, at %s, needs a hand.", "%s, en %s, necesita ayuda.", "%s, em %s, precisa de ajuda.", "%s, à %s, a besoin d'aide.", "%s in %s braucht Hilfe.", "%s（%s）が困っている。", "%s(%s)이(가) 도움을 원한다.", "%s（%s）需要帮忙。"],
    "JOURNAL_BONUS": ["Bonus:", "Extra:", "Extra:", "Bonus :", "Bonus:", "おまけ：", "보너스:", "额外："],
    "JOURNAL_REPEATABLE": ["Repeatable", "Repetible", "Repetível", "Répétable", "Wiederholbar", "繰り返し可", "반복 가능", "可重复"],
    "DURATION_SHORT": ["~5 min", "~5 min", "~5 min", "~5 min", "~5 Min.", "約5分", "약 5분", "约5分钟"],
    "DURATION_MEDIUM": ["~10 min", "~10 min", "~10 min", "~10 min", "~10 Min.", "約10分", "약 10분", "约10分钟"],
    "DURATION_LONG": ["~20 min", "~20 min", "~20 min", "~20 min", "~20 Min.", "約20分", "약 20분", "约20分钟"],
    "BTN_RESTART_STAGE": ["Restart step", "Reiniciar paso", "Reiniciar etapa", "Recommencer l'étape", "Schritt neu starten", "段階をやり直す", "단계 다시 시작", "重新开始此步"],
    # --- Rewards --------------------------------------------------------------------------------------
    "REWARD_JADE": ["◆ %d jade", "◆ %d de jade", "◆ %d de jade", "◆ %d jade", "◆ %d Jade", "◆ 翡翠%d", "◆ 비취 %d", "◆ 翡翠 %d"],
    "REWARD_RECIPE": ["A new recipe", "Una receta nueva", "Uma receita nova", "Une nouvelle recette", "Ein neues Rezept", "新しい料理法", "새로운 요리법", "新食谱"],
    "REWARD_MAP": ["The map fills in", "El mapa se completa", "O mapa se completa", "La carte se complète", "Die Karte füllt sich", "地図が埋まる", "지도가 채워진다", "地图补全了"],
    "REWARD_HEADING": ["Found", "Hallado", "Encontrado", "Trouvé", "Gefunden", "入手", "획득", "获得"],
    "REWARD_BONUS": ["Bonus reward", "Recompensa extra", "Recompensa extra", "Récompense bonus", "Bonusbelohnung", "おまけの報酬", "보너스 보상", "额外奖励"],
    "JADE": ["jade", "jade", "jade", "jade", "Jade", "翡翠", "비취", "翡翠"],
    # --- Encounters / courses -------------------------------------------------------------------------
    "ENC_PROTECT": ["Protect them", "Protégelos", "Proteja-os", "Protégez-les", "Beschütze sie", "守り抜け", "지켜내라", "保护他们"],
    "ENC_SURVIVE": ["Hold out", "Resiste", "Resista", "Tenez bon", "Halte durch", "持ちこたえろ", "버텨라", "坚持住"],
    "ENC_ESCORT": ["Escort", "Escolta", "Escolta", "Escorte", "Geleit", "護衛", "호위", "护送"],
    "ENC_WAVE": ["Wave %d/%d", "Oleada %d/%d", "Onda %d/%d", "Vague %d/%d", "Welle %d/%d", "第%d/%d波", "%d/%d 웨이브", "第%d/%d波"],
    "ENC_METRES_LEFT": ["%d m to go", "Faltan %d m", "Faltam %d m", "Encore %d m", "Noch %d m", "残り%dm", "%dm 남음", "还剩%d米"],
    "ENC_SUCCESS": ["Well done", "Bien hecho", "Muito bem", "Bien joué", "Gut gemacht", "見事だ", "잘했다", "干得好"],
    "ENC_FAILED": ["They got away… or worse.", "Se escaparon… o algo peor.", "Eles fugiram… ou pior.", "Ils ont filé… ou pire.", "Sie sind entkommen… oder Schlimmeres.", "逃げられた…いや、もっと悪い。", "놓쳤다… 아니, 더 나쁘다.", "被他们跑了……或者更糟。"],
    "ENC_RETURN": ["Get back to the spot!", "¡Vuelve al lugar!", "Volte ao local!", "Revenez sur place !", "Zurück zur Stelle!", "持ち場へ戻れ！", "자리로 돌아가!", "回到那里去！"],
    "COURSE_TITLE": ["Wind rings", "Anillos de viento", "Anéis de vento", "Anneaux de vent", "Windringe", "風の輪", "바람의 고리", "风之环"],
    "COURSE_PAR": ["par", "meta", "meta", "objectif", "Ziel", "目標", "목표", "目标"],
    "COURSE_DONE": ["Course done: %.1f s", "Recorrido: %.1f s", "Percurso: %.1f s", "Parcours : %.1f s", "Strecke: %.1f s", "完走：%.1f秒", "완주: %.1f초", "完成：%.1f秒"],
    "COURSE_PAR_BEAT": ["Under par!", "¡Bajo la meta!", "Abaixo da meta!", "Sous l'objectif !", "Unter der Zielzeit!", "目標タイム突破！", "목표 달성!", "低于目标！"],
    "COURSE_PAR_MISSED": ["Try for the par time.", "Intenta bajar de la meta.", "Tente bater a meta.", "Visez l'objectif.", "Versuch die Zielzeit.", "目標タイムを狙え。", "목표 시간에 도전하자.", "争取达到目标时间。"],
    "COURSE_FAILED": ["The rings fade. Start again from the first.", "Los anillos se apagan. Empieza por el primero.", "Os anéis somem. Recomece do primeiro.", "Les anneaux s'éteignent. Recommencez au premier.", "Die Ringe verblassen. Beginne beim ersten.", "輪が消えた。最初からやり直そう。", "고리가 사라졌다. 처음부터 다시.", "风环消散了。从第一个重新开始。"],
    # --- Shouts ------------------------------------------------------------------------------------------
    "SHOUT_HELP": ["Help!", "¡Socorro!", "Socorro!", "À l'aide !", "Hilfe!", "助けて！", "도와줘!", "救命！"],
    "SHOUT_WAIT": ["Wait for me!", "¡Espérame!", "Me espere!", "Attendez-moi !", "Warte auf mich!", "待って！", "기다려!", "等等我！"],
    "SHOUT_AMBUSH": ["Ambush!", "¡Emboscada!", "Emboscada!", "Embuscade !", "Hinterhalt!", "待ち伏せだ！", "매복이다!", "有埋伏！"],
    "SHOUT_THANKS": ["Thank you!", "¡Gracias!", "Obrigado!", "Merci !", "Danke!", "ありがとう！", "고마워!", "谢谢你！"],
    # --- Prompts & hints -----------------------------------------------------------------------------------
    "PROMPT_EXAMINE": ["Examine", "Examinar", "Examinar", "Examiner", "Untersuchen", "調べる", "조사", "调查"],
    "PROMPT_TAKE": ["Take", "Tomar", "Pegar", "Prendre", "Nehmen", "取る", "줍기", "拿取"],
    "PROMPT_FREE": ["Free", "Liberar", "Libertar", "Libérer", "Befreien", "助ける", "풀어주기", "解救"],
    "PROMPT_RING": ["Ring", "Tocar", "Tocar", "Sonner", "Läuten", "鳴らす", "울리기", "敲响"],
    "PROMPT_PULL": ["Pull", "Tirar", "Puxar", "Tirer", "Ziehen", "引く", "당기기", "拉动"],
    "PROMPT_OFFER": ["Offer", "Ofrendar", "Oferecer", "Offrir", "Opfern", "供える", "바치기", "供奉"],
    "PROMPT_LIGHT_BEACON": ["Light the beacon", "Encender la baliza", "Acender o farol", "Allumer le fanal", "Leuchtfeuer entzünden", "灯台に火を", "봉화 밝히기", "点燃烽火"],
    "PROMPT_BOARD": ["Read the board", "Leer el tablón", "Ler o quadro", "Lire le tableau", "Aushang lesen", "掲示板を見る", "게시판 보기", "查看告示"],
    "PROMPT_ALTAR": ["Warden altar", "Altar del Guardián", "Altar do Guardião", "Autel du Gardien", "Hüteraltar", "守り人の祭壇", "지기의 제단", "守风者祭坛"],
    "PROMPT_CALM": ["Calm it", "Calmarlo", "Acalmar", "Le calmer", "Beruhigen", "なだめる", "달래기", "安抚"],
    "PROMPT_PLACE": ["Place", "Colocar", "Colocar", "Poser", "Platzieren", "置く", "놓기", "放置"],
    "HINT_WRONG_TIME": ["Nothing stirs. Perhaps another hour.", "Nada se mueve. Quizá a otra hora.", "Nada se mexe. Talvez em outra hora.", "Rien ne bouge. Peut-être à une autre heure.", "Nichts regt sich. Vielleicht zu anderer Stunde.", "何も起きない。別の時間なら…", "아무 일도 없다. 다른 시간이라면…", "毫无动静。也许换个时辰。"],
    "HINT_WRONG_WEATHER": ["It waits for other weather.", "Espera otro tiempo.", "Espera outro clima.", "Il attend un autre temps.", "Es wartet auf anderes Wetter.", "別の天気を待っているようだ。", "다른 날씨를 기다리는 듯하다.", "它在等待别的天气。"],
    "HINT_NEEDS_ITEM": ["It needs %d × %s.", "Necesita %d × %s.", "Precisa de %d × %s.", "Il faut %d × %s.", "Benötigt %d × %s.", "%d個の%sが必要だ。", "%d × %s이(가) 필요하다.", "需要%d个%s。"],
    "HINT_NEST_FIRE": ["Blades barely scratch it. Fire or a blast would do.", "Las hojas apenas lo arañan. Fuego o una explosión servirían.", "Lâminas mal arranham. Fogo ou explosão resolveriam.", "Les lames l'égratignent à peine. Du feu ou une explosion suffiraient.", "Klingen ritzen es kaum. Feuer oder eine Explosion wirken.", "刃ではほとんど傷つかない。火か爆発なら…", "칼로는 흠집만 난다. 불이나 폭발이면 된다.", "刀刃几乎伤不了它。火或爆炸才行。"],
    "HINT_RUBBLE": ["Solid rock. Something explosive, perhaps.", "Roca maciza. Quizá algo explosivo.", "Rocha sólida. Algo explosivo, talvez.", "Roche massive. Un explosif, peut-être.", "Fester Fels. Vielleicht etwas Explosives.", "硬い岩だ。爆発物なら…", "단단한 바위다. 폭발물이라면…", "坚硬的岩石。也许需要炸药。"],
    # --- Boards & altars -------------------------------------------------------------------------------------
    "BOARD_TITLE": ["Bounty board", "Tablón de encargos", "Quadro de tarefas", "Tableau des primes", "Aushangbrett", "依頼の掲示板", "현상금 게시판", "悬赏告示"],
    "BOARD_HINT": ["New notices every day. Take one, do it, come back richer.", "Nuevos avisos cada día. Toma uno, cúmplelo y vuelve más rico.", "Avisos novos todo dia. Pegue um, cumpra e volte mais rico.", "Nouvelles annonces chaque jour. Prenez-en une, revenez plus riche.", "Täglich neue Aushänge. Nimm einen, erledige ihn, komm reicher zurück.", "毎日新しい依頼が貼られる。引き受けて、稼いでこい。", "매일 새 의뢰가 붙는다. 하나 맡고, 부자가 되어 돌아와라.", "每天都有新告示。接一个，干完回来领赏。"],
    "BOARD_ACCEPT": ["Take it", "Aceptar", "Aceitar", "Accepter", "Annehmen", "引き受ける", "맡기", "接下"],
    "BOARD_TAKEN": ["Taken", "Aceptado", "Aceito", "En cours", "Angenommen", "受注中", "진행 중", "已接"],
    "BOARD_EMPTY": ["Nothing posted today. Come back tomorrow.", "Hoy no hay nada. Vuelve mañana.", "Nada hoje. Volte amanhã.", "Rien aujourd'hui. Revenez demain.", "Heute nichts. Komm morgen wieder.", "今日は何もない。明日また来よう。", "오늘은 없다. 내일 다시 오자.", "今天没有告示，明天再来。"],
    "ALTAR_TITLE": ["Warden altar", "Altar del Guardián", "Altar do Guardião", "Autel du Gardien", "Hüteraltar", "守り人の祭壇", "지기의 제단", "守风者祭坛"],
    "ALTAR_UPGRADES": ["Blessings", "Bendiciones", "Bênçãos", "Bénédictions", "Segen", "加護", "축복", "祝福"],
    "ALTAR_COSMETICS": ["Wind colours", "Colores del viento", "Cores do vento", "Couleurs du vent", "Windfarben", "風の彩り", "바람의 빛깔", "风之色彩"],
    "ALTAR_OFFER": ["Offer ◆ %d", "Ofrecer ◆ %d", "Oferecer ◆ %d", "Offrir ◆ %d", "Opfern ◆ %d", "◆%dを捧げる", "◆ %d 바치기", "献上 ◆ %d"],
    "ALTAR_MAXED": ["Complete", "Completo", "Completo", "Complet", "Vollendet", "極めた", "완성", "已圆满"],
    "ALTAR_BLESSED": ["Blessing received: %s", "Bendición recibida: %s", "Bênção recebida: %s", "Bénédiction reçue : %s", "Segen erhalten: %s", "加護を得た：%s", "축복을 받았다: %s", "获得祝福：%s"],
    "ALTAR_NO_COSMETICS": ["Colours of the wind are found out in the world.", "Los colores del viento se encuentran por el mundo.", "As cores do vento se encontram pelo mundo.", "Les couleurs du vent se trouvent de par le monde.", "Farben des Windes findet man draußen in der Welt.", "風の彩りは世界のどこかで見つかる。", "바람의 빛깔은 세상 곳곳에서 찾을 수 있다.", "风之色彩散落在世界各处。"],
    "COS_DEFAULT": ["Plain", "Sencillo", "Simples", "Simple", "Schlicht", "素のまま", "기본", "朴素"],
    "COS_SLOT_TRAIL": ["Blade trail", "Estela del arma", "Rastro da lâmina", "Traînée de lame", "Klingenspur", "刃の軌跡", "칼날 궤적", "刃光"],
    "COS_SLOT_GLIDER_TRAIL": ["Vela ribbons", "Cintas de la Vela", "Fitas da Vela", "Rubans de la Vela", "Vela-Bänder", "ヴェラの帯", "벨라 리본", "风帆飘带"],
    "COS_SLOT_AFTERIMAGE": ["Dash echo", "Eco del impulso", "Eco do impulso", "Écho de l'élan", "Sprungecho", "疾駆の残像", "질주 잔상", "疾行残影"],
    "UPG_VELA": ["Lighter Vela", "Vela ligera", "Vela leve", "Vela allégée", "Leichte Vela", "軽やかなヴェラ", "가벼운 벨라", "轻盈风帆"],
    "UPG_VELA_DESC": ["Gliding tires you 12% less per blessing.", "Planear cansa un 12% menos por bendición.", "Planar cansa 12% menos por bênção.", "Planer fatigue 12 % de moins par bénédiction.", "Gleiten ermüdet pro Segen 12 % weniger.", "加護ごとに滑空の疲れが12%減る。", "축복마다 활공 피로 12% 감소.", "每层祝福滑翔消耗减少12%。"],
    "UPG_BREATH": ["Deep breath", "Aliento hondo", "Fôlego fundo", "Souffle profond", "Tiefer Atem", "深い息", "깊은 숨", "深息"],
    "UPG_BREATH_DESC": ["+20 stamina per blessing.", "+20 de aguante por bendición.", "+20 de vigor por bênção.", "+20 d'endurance par bénédiction.", "+20 Ausdauer pro Segen.", "加護ごとにがんばり+20。", "축복마다 기력 +20.", "每层祝福耐力+20。"],
    "UPG_HEART": ["Warden's heart", "Corazón del Guardián", "Coração do Guardião", "Cœur du Gardien", "Hüterherz", "守り人の心", "지기의 심장", "守风者之心"],
    "UPG_HEART_DESC": ["+20 health per blessing.", "+20 de vida por bendición.", "+20 de vida por bênção.", "+20 de vie par bénédiction.", "+20 Leben pro Segen.", "加護ごとに体力+20。", "축복마다 체력 +20.", "每层祝福生命+20。"],
    "UPG_WINDS": ["Swift winds", "Vientos raudos", "Ventos velozes", "Vents rapides", "Schnelle Winde", "疾き風", "빠른 바람", "疾风"],
    "UPG_WINDS_DESC": ["Warden arts recover 12% faster per blessing.", "Las artes del Guardián se recargan un 12% antes.", "As artes do Guardião recarregam 12% mais rápido.", "Les arts du Gardien reviennent 12 % plus vite.", "Hüterkünste laden pro Segen 12 % schneller.", "加護ごとに技の回復が12%速まる。", "축복마다 기술 재사용 12% 단축.", "每层祝福技能冷却缩短12%。"],
    "UPG_EDGE": ["Steady edge", "Filo firme", "Fio firme", "Tranchant sûr", "Feste Schneide", "揺るがぬ刃", "굳건한 날", "坚刃"],
    "UPG_EDGE_DESC": ["Weapons wear 15% slower per blessing.", "Las armas se gastan un 15% menos.", "As armas se desgastam 15% menos.", "Les armes s'usent 15 % moins vite.", "Waffen nutzen pro Segen 15 % langsamer ab.", "加護ごとに武器の消耗が15%減る。", "축복마다 무기 마모 15% 감소.", "每层祝福武器损耗减少15%。"],
    "COS_TRAIL_EMBER": ["Ember trail", "Estela de brasa", "Rastro de brasa", "Traînée de braise", "Glutspur", "熾火の軌跡", "불씨 궤적", "余烬刃光"],
    "COS_TRAIL_JADE": ["Jade trail", "Estela de jade", "Rastro de jade", "Traînée de jade", "Jadespur", "翡翠の軌跡", "비취 궤적", "翡翠刃光"],
    "COS_TRAIL_FROST": ["Frost trail", "Estela de escarcha", "Rastro de geada", "Traînée de givre", "Frostspur", "霜の軌跡", "서리 궤적", "霜华刃光"],
    "COS_TRAIL_DUSK": ["Dusk trail", "Estela del ocaso", "Rastro do crepúsculo", "Traînée du crépuscule", "Dämmerspur", "黄昏の軌跡", "황혼 궤적", "暮色刃光"],
    "COS_TRAIL_GILT": ["Gilded trail", "Estela dorada", "Rastro dourado", "Traînée dorée", "Goldspur", "金の軌跡", "황금 궤적", "鎏金刃光"],
    "COS_RIBBON_CINNABAR": ["Cinnabar ribbons", "Cintas de cinabrio", "Fitas de cinábrio", "Rubans vermillon", "Zinnoberbänder", "朱の帯", "주홍 리본", "朱砂飘带"],
    "COS_RIBBON_JADE": ["Jade ribbons", "Cintas de jade", "Fitas de jade", "Rubans de jade", "Jadebänder", "翡翠の帯", "비취 리본", "翡翠飘带"],
    "COS_RIBBON_DAWN": ["Dawn ribbons", "Cintas del alba", "Fitas da aurora", "Rubans de l'aube", "Morgenbänder", "暁の帯", "새벽 리본", "晨曦飘带"],
    "COS_RIBBON_STAR": ["Starlight ribbons", "Cintas de estrellas", "Fitas estelares", "Rubans d'étoiles", "Sternenbänder", "星明かりの帯", "별빛 리본", "星光飘带"],
    "COS_ECHO_SAND": ["Sand echo", "Eco de arena", "Eco de areia", "Écho de sable", "Sandecho", "砂の残像", "모래 잔상", "流沙残影"],
    "COS_ECHO_VEIL": ["Veil echo", "Eco del Velo", "Eco do Véu", "Écho du Voile", "Schleierecho", "帳の残像", "장막 잔상", "帷幕残影"],
    "COS_ECHO_STORM": ["Storm echo", "Eco de tormenta", "Eco da tempestade", "Écho d'orage", "Sturmecho", "嵐の残像", "폭풍 잔상", "雷暴残影"],
}
