"""Far-sea quests (phase 4.5): two, each teaching one sea. Everything else
in the Mist Sea and the Current Sea stays outside the journal.
Neither needs the Bellhull: the bells line starts a swim from the west
shore; the Great Rip carries a swimmer, the spout launches one."""
from qdsl import L, T, quest, stage, obj
import far_seas

QUESTS = []
Q = QUESTS.append

B1 = list(far_seas.BELLS[0][1])
SANCT = [-1255, 30]
RIP_END = list(far_seas.RIP_END)
HIGH = [1345, 880]

# --- Voices in the Mist: navigate by ear ------------------------------------------------------------------
Q(quest("sq_mist_voices", "side", "exploration", "coast", 3, "medium",
    L("Voices in the Mist", "Voces en la bruma", "Vozes na bruma", "Voix dans la brume", "Stimmen im Nebel", "霧の声", "안개 속의 목소리", "雾中之声"),
    L("West of Tide Isle the mist comes in every night. The bell-keepers who rang ships home through it are gone — their bells are not.", "Al oeste de la Isla de las Mareas la bruma llega cada noche. Los campaneros que guiaban a los barcos ya no están; sus campanas sí.", "A oeste da Ilha das Marés a bruma chega toda noite. Os sineiros que guiavam os navios se foram — os sinos não.", "À l'ouest de l'Île des Marées, la brume vient chaque nuit. Les sonneurs ne sont plus là — leurs cloches, si.", "Westlich der Gezeiteninsel kommt jede Nacht der Nebel. Die Glöckner sind fort — ihre Glocken nicht.", "潮の島の西は毎晩霧に包まれる。鐘守りはもういないが、鐘は残っている。", "조수의 섬 서쪽엔 밤마다 안개가 온다. 종지기들은 떠났지만 종은 남았다.", "潮汐岛以西每晚起雾。守钟人不在了，钟还在。"),
    [stage(obj("talk", "NPC_TIDEKEEPER", T("QO_T_TALK", "NAME_TIDEKEEPER")),
           talk=[L("Go at dusk, when the mist is in. Find the first bell by its lamp at the edge of the white, ring it, and listen for which one answers.", "Ve al atardecer, con la bruma. Encuentra la primera campana por su farol al borde del blanco, tócala y escucha cuál responde.", "Vá ao entardecer, com a bruma. Ache o primeiro sino pela lanterna na borda do branco, toque-o e escute qual responde.", "Va au crépuscule, quand la brume est là. Trouve la première cloche à sa lanterne au bord du blanc, sonne-la et écoute laquelle répond.", "Geh in der Dämmerung, wenn der Nebel da ist. Finde die erste Glocke an ihrer Lampe am Rand des Weißen, läute und horch, welche antwortet.", "霧の出る夕暮れに行け。白の縁の灯で最初の鐘を見つけ、鳴らし、どれが応えるか聞け。", "안개 낀 해 질 녘에 가. 하얀 가장자리의 등불로 첫 종을 찾아 치고, 어느 종이 대답하는지 들어.", "黄昏起雾时去。在白雾边上凭灯找到第一口钟，敲响，听哪一口回应。")]),
     stage(obj("reach", "", T("QO_T_REACH", L("the first fog bell", "la primera campana de niebla", "o primeiro sino da névoa", "la première cloche de brume", "die erste Nebelglocke", "最初の霧の鐘", "첫 번째 안개 종", "第一口雾钟")), pos=B1, radius=10.0, marker=B1)),
     stage(obj("flag", "mist_bells_answered", T("QO_T_RING", L("the bells, one by one", "las campanas, una a una", "os sinos, um a um", "les cloches, une à une", "die Glocken, eine nach der anderen", "鐘を一つずつ", "종을 하나씩", "一口接一口的钟"))),
           hint=[L("Each bell you ring makes the next one answer — a toll and a flare of its lamp in the white.", "Cada campana que tocas hace responder a la siguiente: un tañido y un destello de su farol en el blanco.", "Cada sino que você toca faz o próximo responder — um toque e um clarão da lanterna no branco.", "Chaque cloche sonnée fait répondre la suivante — un coup et un éclat de sa lanterne dans le blanc.", "Jede geläutete Glocke lässt die nächste antworten — ein Schlag und ein Aufleuchten ihrer Lampe im Weiß.", "鳴らすたびに次の鐘が応える。白の中に鐘の音と灯のきらめき。", "종을 칠 때마다 다음 종이 대답한다. 하얀 속에서 울림과 등불의 번쩍임.", "每敲一口，下一口就会回应——白雾里一声钟响，一闪灯光。")]),
     stage(obj("open_chest", "bell_sanctuary:altar", T("QO_T_OPEN", L("the altar of the bells", "el altar de las campanas", "o altar dos sinos", "l'autel des cloches", "den Altar der Glocken", "鐘の祭壇", "종의 제단", "钟之祭坛")), marker=SANCT)),
     stage(obj("talk", "NPC_TIDEKEEPER", T("QO_T_RETURN", "NAME_TIDEKEEPER")),
           talk=[L("The keepers' lamp. With it the mist is only half as thick. My grandmother said they could hear a ship's wake in it.", "El farol de los guardianes. Con él la bruma es la mitad de espesa. Mi abuela decía que oían la estela de un barco en ella.", "A lanterna dos guardiões. Com ela a bruma é metade da espessura. Minha avó dizia que ouviam a esteira de um navio nela.", "La lampe des gardiens. Avec elle, la brume est moitié moins épaisse. Ma grand-mère disait qu'ils y entendaient le sillage d'un navire.", "Die Lampe der Hüter. Mit ihr ist der Nebel nur halb so dicht. Meine Großmutter sagte, sie hörten darin das Kielwasser eines Schiffs.", "鐘守りの灯だ。これがあれば霧は半分の濃さ。祖母は彼らが霧の中で船の航跡を聞けたと言っていた。", "종지기의 등불이야. 이걸로 안개가 절반만큼 옅어져. 할머니는 그들이 안개 속에서 배의 물결 소리를 들었다고 했지.", "守钟人的灯。有了它雾只剩一半厚。我祖母说他们能在雾里听见船的尾浪。")])],
    {"glimmer": 60, "jade": 2},
    start="talk:NPC_TIDEKEEPER", requires=["sq_sea_first_crossing"],
    offer_lines=[L("Have you heard the bells west of Tide Isle? Nobody has rung them in thirty years. Somebody is ringing them now — or something.", "¿Has oído las campanas al oeste de la Isla de las Mareas? Nadie las toca desde hace treinta años. Alguien las toca ahora... o algo.", "Ouviu os sinos a oeste da Ilha das Marés? Ninguém os toca há trinta anos. Alguém os toca agora — ou algo.", "As-tu entendu les cloches à l'ouest de l'Île des Marées ? Personne ne les sonne depuis trente ans. Quelqu'un les sonne — ou quelque chose.", "Hast du die Glocken westlich der Gezeiteninsel gehört? Seit dreißig Jahren läutet sie keiner. Jetzt läutet sie jemand — oder etwas.", "潮の島の西の鐘を聞いたか。三十年誰も鳴らしていない。今誰かが鳴らしている…何かが。", "조수의 섬 서쪽 종소리 들었어? 삼십 년 동안 아무도 안 쳤는데. 지금 누가 치고 있어. 아니면 뭔가가.", "听见潮汐岛西边的钟声了吗？三十年没人敲了。现在有人在敲——或者有什么在敲。")]))

# --- The Road in the Sea: use the currents ----------------------------------------------------------------
Q(quest("sq_rip_road", "side", "traversal", "desert", 3, "medium",
    L("The Road in the Sea", "El camino en el mar", "A estrada no mar", "La route dans la mer", "Die Straße im Meer", "海の道", "바다의 길", "海中之路"),
    L("The nomads say the sea below the southern cliffs runs like a river twice a day. Ride it, and the Wind Rock will throw you to the High Isle.", "Los nómadas dicen que el mar bajo los acantilados del sur corre como un río dos veces al día. Móntalo y la Roca del Viento te lanzará a la Isla Alta.", "Os nômades dizem que o mar sob as falésias do sul corre como rio duas vezes ao dia. Monte-o e a Rocha do Vento te lançará à Ilha Alta.", "Les nomades disent que la mer sous les falaises du sud coule comme un fleuve deux fois par jour. Suis-la, et le Rocher du Vent te jettera sur l'Île haute.", "Die Nomaden sagen, das Meer unter den Südklippen fließt zweimal am Tag wie ein Fluss. Reite es, und der Windfels wirft dich auf die Hohe Insel.", "遊牧民いわく南の崖下の海は日に二度川になる。乗れば風の岩が高き島へ放り上げる。", "유목민들은 남쪽 절벽 아래 바다가 하루 두 번 강처럼 흐른다고 한다. 타면 바람 바위가 높은 섬으로 던져 준다.", "游牧人说南崖下的海一天两次像河一样流。顺着它走，风岩会把你抛上高岛。"),
    [stage(obj("talk", "NPC_NOMAD", T("QO_T_TALK", "NAME_NOMAD")),
           talk=[L("Wait until the water runs — between the tides — then jump in under the cliffs and let it carry you east. Fighting it is for fools.", "Espera a que el agua corra, entre mareas; luego lánzate bajo los acantilados y deja que te lleve al este. Luchar contra ella es de necios.", "Espere a água correr — entre as marés — e pule sob as falésias e deixe-a levar você a leste. Lutar contra ela é coisa de tolo.", "Attends que l'eau coure — entre deux marées — puis saute sous les falaises et laisse-la t'emporter à l'est. La combattre, c'est pour les fous.", "Warte, bis das Wasser läuft — zwischen den Gezeiten —, dann spring unter den Klippen hinein und lass dich nach Osten tragen. Dagegen kämpfen nur Narren.", "潮と潮の間、水が走る時を待て。崖下に飛び込み東へ運ばれろ。逆らうのは愚か者だ。", "조수 사이 물이 흐를 때를 기다려. 절벽 아래로 뛰어들어 동쪽으로 실려 가. 거스르는 건 바보짓이야.", "等水流起来——两潮之间——从崖下跳进去，让它把你往东带。跟它较劲是傻子干的事。")]),
     stage(obj("reach", "", T("QO_T_REACH", "DISC_RIP_GREAT"), pos=RIP_END, radius=30.0, marker=RIP_END),
           hint=[L("The Rip is weak at slack water, around 6, 12, 18 and midnight. It runs hardest in between.", "La Resaca es débil en el repunte, hacia las 6, 12, 18 y medianoche. Corre más entre medias.", "A Ressaca é fraca no estofo, perto das 6, 12, 18 e meia-noite. Corre mais no meio.", "Le Courant faiblit à l'étale, vers 6, 12, 18 h et minuit. Il file surtout entre les deux.", "Der Sog ist bei Stauwasser schwach, um 6, 12, 18 Uhr und Mitternacht. Dazwischen läuft er am stärksten.", "潮筋は潮止まり（6、12、18時と真夜中）に弱く、その間に最も速い。", "역조는 정조(6시, 12시, 18시, 자정 무렵)에 약하고 그 사이에 가장 세다.", "平潮时（6点、12点、18点、午夜前后）激流最弱，中间最急。")]),
     stage(obj("reach", "", T("QO_T_REACH", "DISC_RIP_HIGH_ISLE"), pos=HIGH, radius=24.0, min_y=26.0, marker=HIGH),
           hint=[L("Swim to the Wind Rock's foot when the water boils, open your sail when the sea throws you up, and let the wind over the rock lift you.", "Nada al pie de la Roca del Viento cuando el agua hierva, abre la vela cuando el mar te lance y deja que el viento de la roca te eleve.", "Nade ao pé da Rocha do Vento quando a água ferver, abra a vela quando o mar te lançar e deixe o vento da rocha te erguer.", "Nage au pied du Rocher du Vent quand l'eau bout, ouvre la voile quand la mer te lance, et laisse le vent du rocher te porter.", "Schwimm zum Fuß des Windfelsens, wenn das Wasser kocht, öffne das Segel, wenn das Meer dich hochwirft, und lass dich vom Wind am Fels heben.", "水が沸いたら風の岩の麓へ泳ぎ、海に放り上げられたら帆を開き、岩の風に乗れ。", "물이 끓을 때 바람 바위 발치로 헤엄쳐, 바다가 던져 올리면 돛을 펴고 바위의 바람을 타.", "水冒泡时游到风岩脚下，海把你抛起来就张帆，让岩上的风托着你。")]),
     stage(obj("talk", "NPC_NOMAD", T("QO_T_RETURN", "NAME_NOMAD")),
           talk=[L("You flew off the sea! Then the current knows you now. Come back when it runs — it never runs the same road twice in a day.", "¡Volaste desde el mar! Entonces la corriente ya te conoce. Vuelve cuando corra: nunca corre igual dos veces al día.", "Você voou do mar! Então a corrente já te conhece. Volte quando correr — nunca corre igual duas vezes no dia.", "Tu t'es envolé depuis la mer ! Alors le courant te connaît. Reviens quand il court — il ne court jamais pareil deux fois par jour.", "Du bist vom Meer aus geflogen! Dann kennt dich die Strömung jetzt. Komm wieder, wenn sie läuft — sie läuft nie zweimal gleich am Tag.", "海から飛んだのか！なら潮はもうお前を知っている。流れる時にまた来い。日に二度同じ道は流れない。", "바다에서 날아올랐다고! 그럼 해류가 이제 널 알아. 흐를 때 또 와. 하루에 두 번 같은 길로 흐르진 않거든.", "你从海上飞起来了！那激流已经认得你了。水流时再来——它一天从不走同一条路两次。")])],
    {"glimmer": 60, "jade": 2, "items": [{"id": "rip_mackerel", "count": 2}]},
    start="talk:NPC_NOMAD",
    offer_lines=[L("See the white seam on the sea under the cliffs? That's a road, twice a day. My grandfather crossed to the High Isle on it — and flew.", "¿Ves la costura blanca en el mar bajo los acantilados? Es un camino, dos veces al día. Mi abuelo cruzó por ahí a la Isla Alta... y voló.", "Vê a costura branca no mar sob as falésias? É uma estrada, duas vezes ao dia. Meu avô cruzou por ela até a Ilha Alta — e voou.", "Tu vois la couture blanche sur la mer sous les falaises ? C'est une route, deux fois par jour. Mon grand-père l'a prise jusqu'à l'Île haute — et il a volé.", "Siehst du die weiße Naht auf dem Meer unter den Klippen? Das ist eine Straße, zweimal am Tag. Mein Großvater kam darauf zur Hohen Insel — und flog.", "崖下の海の白い縫い目が見えるか。日に二度の道だ。祖父はそれで高き島へ渡り、飛んだ。", "절벽 아래 바다의 흰 솔기 보여? 하루 두 번 열리는 길이야. 할아버지는 그걸 타고 높은 섬에 갔지. 날아서.", "看见崖下海上那道白缝了吗？那是一天两次的路。我祖父顺着它去了高岛——还飞了起来。")]))
