"""Highlands and mountain: offerings on the peak, cold climbers, a quarry
guardian, a storm-charged rod and a frozen shrine that wants fire."""
from qdsl import L, T, quest, stage, obj

QUESTS = []
Q = QUESTS.append

Q(quest("sq_summit_offering", "side", "traversal", "highlands", 3, "long",
    L("An Offering at the Summit", "Una ofrenda en la cumbre", "Uma oferenda no cume", "Une offrande au sommet", "Ein Opfer auf dem Gipfel", "頂の供え物", "정상의 공물", "峰顶供奉"),
    L("Old Wen is too old for the climb. He asks you to leave honeycomb at Cendal's peak cairn.", "El viejo Wen ya no puede subir. Te pide que dejes un panal en el hito de la cumbre de Cendal.", "O velho Wen já não sobe. Pede que você deixe um favo no marco do cume de Cendal.", "Le vieux Wen ne peut plus grimper. Il vous prie de déposer un rayon de miel au cairn du Cendal.", "Der alte Wen schafft den Aufstieg nicht mehr. Leg eine Wabe am Gipfelsteinmann des Cendal ab.", "ウェン老はもう登れない。センダル山頂の石塚に蜂の巣を供えてほしいと。", "웬 노인은 이제 못 오른다. 센달 정상 돌무더기에 벌집을 놓아 달란다.", "老温爬不动了，托你把蜂巢供在森达尔峰顶的石堆上。"),
    [stage(obj("interact", "summit_offering", L("Leave honeycomb at the peak cairn", "Deja un panal en el hito de la cumbre", "Deixe um favo no marco do cume", "Déposez un rayon de miel au cairn", "Leg eine Wabe am Gipfelsteinmann ab", "山頂の石塚に蜂の巣を供える", "정상 돌무더기에 벌집 놓기", "把蜂巢供在峰顶石堆"), marker=[-103, -573]),
           spawns=[{"kind": "object", "id": "summit_offering", "look": "offering", "poi": "cendal_summit", "pos": [-2.2, 1.8], "needs_item": "honeycomb", "needs_count": 1, "prompt": "PROMPT_OFFER", "element": "jade", "hide_used": False, "range": 220,
                    "lines": [L("The wind drops for a moment, as if listening. Then it blows warm.", "El viento se calma un instante, como si escuchara. Luego sopla cálido.", "O vento para por um instante, como se escutasse. Depois sopra morno.", "Le vent tombe un instant, comme s'il écoutait. Puis il souffle, tiède.", "Der Wind legt sich kurz, als lausche er. Dann weht er warm.", "風が一瞬止み、耳を澄ますよう。やがて温かく吹く。", "바람이 잠시 멎는다, 귀 기울이듯. 이내 따뜻하게 분다.", "风停了一瞬，像在倾听，随即吹来一阵暖意。")]}]),
     stage(obj("talk", "NPC_HERMIT", T("QO_T_RETURN", "NAME_HERMIT")),
           talk=[L("You felt it too? Then the peak remembers us. Wear this; it sparkles like old snow.", "¿Tú también lo sentiste? Entonces la cumbre nos recuerda. Lleva esto; brilla como nieve vieja.", "Você também sentiu? Então o cume se lembra de nós. Use isto; brilha como neve antiga.", "Vous l'avez senti aussi ? Alors le sommet se souvient. Portez ceci, ça scintille comme la vieille neige.", "Du hast es auch gespürt? Dann erinnert sich der Gipfel. Trag das, es glitzert wie alter Schnee.", "お前も感じたか。頂は我らを覚えている。これを。古い雪のように光る。", "너도 느꼈나? 그럼 정상이 우릴 기억하는 거다. 이걸 달아라, 묵은 눈처럼 반짝인다.", "你也感觉到了？那山顶还记得我们。戴上这个，亮得像陈雪。")])],
    {"cosmetic": "ribbon_star", "jade": 2},
    start="talk:NPC_HERMIT",
    offer_lines=[L("My knees won't do Cendal anymore. Take honeycomb to the cairn for me? The wind likes sweet things.", "Mis rodillas ya no suben al Cendal. ¿Llevas un panal al hito por mí? Al viento le gusta lo dulce.", "Meus joelhos não sobem mais o Cendal. Leva um favo ao marco? O vento gosta de doce.", "Mes genoux ne font plus le Cendal. Portez un rayon au cairn ? Le vent aime le sucré.", "Meine Knie schaffen den Cendal nicht mehr. Bringst du Waben zum Steinmann? Der Wind mag Süßes.", "膝がもうセンダルに登れん。石塚に蜂の巣を頼む。風は甘いものが好きでな。", "무릎이 센달을 못 오른다. 돌무더기에 벌집 좀 놔 주겠나? 바람은 단 걸 좋아하지.", "我这膝盖上不了森达尔了。替我把蜂巢送到石堆？风爱吃甜的。")]))

Q(quest("sq_warm_hearts", "side", "gathering", "highlands", 2, "medium",
    L("Warm Hearts", "Corazones cálidos", "Corações quentes", "Cœurs chauds", "Warme Herzen", "温かい心", "따뜻한 마음", "暖心"),
    L("Kest's camp is freezing and her crew is out of food. A spicy curry would get them climbing again.", "El campamento de Kest se congela y su equipo no tiene comida. Un curry picante los haría escalar de nuevo.", "O acampamento de Kest congela e a equipe está sem comida. Um curry picante os faria escalar de novo.", "Le camp de Kest gèle et l'équipe n'a plus rien. Un curry épicé les remettrait à grimper.", "Kests Lager friert, der Truppe fehlt Essen. Ein scharfes Curry brächte sie wieder an den Fels.", "ケストの野営地は凍え、食料も尽きた。辛いカレーでまた登れる。", "케스트의 야영지는 얼어붙고 식량도 떨어졌다. 매운 카레면 다시 오를 거다.", "凯丝特的营地冻得够呛，也断了粮。一锅辣咖喱能让大家重新攀岩。"),
    [stage(obj("cook", "warming_curry", T("QO_T_COOK", "ITEM_WARMING_CURRY")),
           hint=[L("Emberroot gives the heat. It grows on the high slopes.", "La raíz ígnea da el calor. Crece en las laderas altas.", "A raiz-brasa dá o calor. Cresce nas encostas altas.", "La racine-braise donne la chaleur. Elle pousse sur les hauts versants.", "Glutwurz bringt die Wärme. Sie wächst an den hohen Hängen.", "熾根が熱をくれる。高い斜面に生える。", "불씨뿌리가 열을 낸다. 높은 비탈에서 자란다.", "烬根给热量，长在高坡上。")]),
     stage(obj("deliver", "NPC_CLIMBER", T("QO_T_GIVE", "ITEM_WARMING_CURRY", "NAME_CLIMBER"), item="warming_curry"),
           talk=[L("Oh, that burns. Perfect. Take my spare gloves — you climb like you mean it.", "Uf, cómo pica. Perfecto. Toma mis guantes de repuesto, escalas con ganas.", "Nossa, arde. Perfeito. Fique com minhas luvas extras, você escala com vontade.", "Oh, ça brûle. Parfait. Prenez mes gants de rechange, vous grimpez avec cœur.", "Oh, das brennt. Perfekt. Nimm meine Ersatzhandschuhe — du kletterst mit Herz.", "おお、辛い。最高だ。予備の手袋をやる、いい登りっぷりだ。", "와, 맵다. 완벽해. 여분 장갑 가져가, 제대로 오르더라.", "哇，真辣，正好。我的备用手套给你，你爬得有劲。")])],
    {"items": [{"id": "climber_gloves", "count": 1}], "jade": 1},
    start="talk:NPC_CLIMBER",
    offer_lines=[L("My crew's shaking too hard to grip. Something hot and spicy, please — curry, if you can.", "Mi equipo tiembla tanto que no puede agarrarse. Algo caliente y picante, por favor; curry, si puedes.", "Minha equipe treme demais para segurar. Algo quente e picante, por favor; curry, se puder.", "Mon équipe tremble trop pour tenir. Du chaud et épicé, s'il vous plaît — un curry, si possible.", "Meine Leute zittern zu sehr zum Greifen. Etwas Heißes, Scharfes — Curry, wenn du kannst.", "仲間が震えて握れない。熱くて辛いもの、できればカレーを。", "대원들이 떨려서 못 잡아. 뜨겁고 매운 거, 되도록 카레로.", "队员冷得抓不住岩。来点又热又辣的，最好是咖喱。")]))

Q(quest("dq_stoneward", "discovery", "boss", "valley", 3, "short",
    L("The Quarry Guardian", "El guardián de la cantera", "O guardião da pedreira", "Le gardien de la carrière", "Der Steinbruchwächter", "石切り場の番人", "채석장의 파수꾼", "采石场守卫"),
    L("Something made of cut stone still walks the old quarry, guarding iron nobody has mined in a century.", "Algo hecho de piedra tallada aún recorre la cantera vieja, guardando hierro que nadie extrae desde hace un siglo.", "Algo de pedra talhada ainda anda pela pedreira velha, guardando ferro que ninguém extrai há um século.", "Une chose de pierre taillée arpente encore la vieille carrière, gardant un fer que nul n'extrait depuis un siècle.", "Etwas aus behauenem Stein wandelt noch im alten Steinbruch und bewacht Eisen, das seit einem Jahrhundert keiner abbaut.", "切り石でできた何かが今も古い石切り場を歩き、百年誰も掘らない鉄を守っている。", "깎은 돌로 된 무언가가 아직도 옛 채석장을 걸으며 백 년간 아무도 캐지 않은 철을 지킨다.", "一个石砌之物仍在旧采石场游荡，守着百年无人开采的铁。"),
    [stage(obj("boss", "BOSS_STONEWARD", T("QO_T_DEFEAT", "NAME_STONEWARD"), marker=[-330, -296]))],
    {"jade": 2, "glimmer": 60},
    start="poi:old_quarry"))

Q(quest("sq_storm_rod", "side", "exploration", "lakeshore", 3, "medium",
    L("The Storm Rod", "La vara de tormenta", "A vara da tempestade", "La verge d'orage", "Der Sturmstab", "嵐の杖", "폭풍 막대", "引雷杖"),
    L("Hadda wants a storm core: touch the old rod on the Broken Tower while lightning is in the air.", "Hadda quiere un núcleo de tormenta: toca la vieja vara de la Torre Rota cuando haya rayos.", "Hadda quer um núcleo de tempestade: toque a velha vara da Torre Partida quando houver raios.", "Hadda veut un cœur d'orage : touchez la vieille verge de la Tour brisée quand la foudre gronde.", "Hadda will einen Sturmkern: berühre den alten Stab auf dem Zerbrochenen Turm, wenn Blitze zucken.", "ハッダは嵐の核が欲しい。雷の日に崩れ塔の古い杖に触れよ。", "하다는 폭풍 핵을 원한다. 번개 치는 날 부서진 탑의 낡은 막대를 만져라.", "哈达想要雷暴之核：打雷时去摸断塔上的旧杖。"),
    [stage(obj("climb", "broken_tower", L("Climb the Broken Tower in a storm", "Escala la Torre Rota durante una tormenta", "Escale a Torre Partida numa tempestade", "Escaladez la Tour brisée pendant un orage", "Erklimm den Zerbrochenen Turm im Sturm", "嵐の中で崩れ塔に登る", "폭풍 속에 부서진 탑 오르기", "在雷雨中攀上断塔"), radius=10.0, min_y=12.0, conditions={"weather": ["storm"]}, marker=[-330, -60])),
     stage(obj("retrieve", "storm_rod", T("QO_T_TAKE", "ITEM_CHARGED_CORE"), marker=[-330, -60], conditions={"weather": ["storm"]}),
           spawns=[{"kind": "object", "id": "storm_rod", "look": "lever", "poi": "broken_tower", "pos": [0.8, 0.6], "snap": "top", "min_y": 9.0, "item": "charged_core", "prompt": "PROMPT_PULL", "element": "electric", "range": 200,
                    "conditions": {"weather": ["storm"]}, "hint_key": "HINT_WRONG_WEATHER"}]),
     stage(obj("deliver", "NPC_SMITH", T("QO_T_GIVE", "ITEM_CHARGED_CORE", "NAME_SMITH"), item="charged_core"),
           talk=[L("Still humming! This goes in a charm that laughs at lightning. It's yours.", "¡Aún zumba! Esto va en un amuleto que se ríe de los rayos. Es tuyo.", "Ainda zumbe! Isto vai num amuleto que ri dos raios. É seu.", "Ça bourdonne encore ! Ça ira dans un charme qui se rit de la foudre. Il est à vous.", "Summt noch! Das kommt in einen Talisman, der über Blitze lacht. Er gehört dir.", "まだ唸ってる！雷を笑う護符にしてやる。お前のだ。", "아직 윙윙대! 번개를 비웃는 부적에 넣어 주지. 네 거야.", "还在嗡嗡响！做成个不怕雷的护符，归你了。")])],
    {"items": [{"id": "lodestone_charm", "count": 1}], "jade": 2},
    start="talk:NPC_SMITH", requires=["sq_arsenal"],
    offer_lines=[L("There's a rod on the Broken Tower that drinks lightning. Next storm, climb up and bring me what it holds.", "En la Torre Rota hay una vara que bebe rayos. En la próxima tormenta, sube y tráeme lo que guarde.", "Na Torre Partida há uma vara que bebe raios. Na próxima tempestade, suba e traga o que ela guarda.", "Sur la Tour brisée, une verge boit la foudre. Au prochain orage, grimpez et rapportez ce qu'elle contient.", "Auf dem Zerbrochenen Turm trinkt ein Stab Blitze. Beim nächsten Sturm hinauf und bring mir, was er hält.", "崩れ塔に雷を飲む杖がある。次の嵐に登って、中身を持ってこい。", "부서진 탑에 번개를 마시는 막대가 있어. 다음 폭풍에 올라가서 가져와.", "断塔上有根吸雷的杖。下次打雷，爬上去把里面的东西拿来。")]))

Q(quest("dq_frost_shrine", "discovery", "puzzle", "highlands", 3, "medium",
    L("The Frozen Shrine", "El santuario helado", "O santuário congelado", "Le sanctuaire gelé", "Der gefrorene Schrein", "凍てつく祠", "얼어붙은 사당", "冰封神祠"),
    L("High on the mountain, a shrine sleeps under frost. Its braziers are cold and its vane won't turn.", "En lo alto de la montaña, un santuario duerme bajo la escarcha. Sus braseros están fríos y su veleta no gira.", "No alto da montanha, um santuário dorme sob a geada. Os braseiros estão frios e o cata-vento não gira.", "Haut sur la montagne, un sanctuaire dort sous le givre. Braseros froids, girouette figée.", "Hoch am Berg schläft ein Schrein unter Frost. Die Becken sind kalt, die Fahne dreht sich nicht.", "山の高みに霜の下で眠る祠。火鉢は冷え、風見は回らない。", "산 높은 곳, 서리 아래 잠든 사당. 화로는 식고 바람개비는 돌지 않는다.", "山巅有座神祠沉睡在霜下，火盆冰冷，风向标不转。"),
    [stage(obj("puzzle", "frost_seal", T("QO_T_SOLVE", "POI_FROST_SHRINE"), marker=[-150, -500]),
           hint=[L("Fire must be carried up here: the ember rod, flint, or a burning branch. And the vane wants wind.", "El fuego hay que subirlo: la vara ígnea, pedernal o una rama ardiendo. Y la veleta quiere viento.", "O fogo precisa ser trazido: o bastão ígneo, pederneira ou um galho em chamas. E o cata-vento quer vento.", "Il faut monter le feu : bâton de braise, silex, ou branche en feu. Et la girouette veut du vent.", "Feuer muss hinaufgetragen werden: Glutstab, Feuerstein oder ein brennender Ast. Und die Fahne will Wind.", "火を運び上げねば：熾の杖か火打ち石か燃える枝。風見には風を。", "불을 들고 올라와야 한다: 불씨 막대, 부싯돌, 불붙은 가지. 바람개비엔 바람을.", "火得带上来：烬杖、燧石或燃枝。风向标要的是风。")]),
     stage(obj("open_chest", "frost_seal:chest", T("QO_T_OPEN", L("the shrine's offering chest", "el cofre de ofrendas", "o baú de oferendas", "le coffre d'offrandes", "die Opfertruhe", "祠の供物箱", "사당의 공물 상자", "神祠供箱"))))],
    {"jade": 2},
    start="poi:frost_shrine",
    spawns=[{"kind": "puzzle", "id": "frost_seal", "poi": "frost_shrine", "pos": [0, 0], "when": "open",
             "elements": [{"type": "brazier", "at": [6, 4]}, {"type": "brazier", "at": [-6, 4]}, {"type": "brazier", "at": [0, -7]}, {"type": "vane", "at": [5, -5]}],
             "seal": {"at": [-6.5, -4], "chest": {"id": "frost_seal:chest", "table": "chest_rare", "items": [{"id": "stamina_bloom", "count": 1}, {"id": "woolen_wrap", "count": 1}]}}}]))

Q(quest("sq_hermit_pantry", "side", "gathering", "highlands", 2, "medium",
    L("Old Wen's Pantry", "La despensa del viejo Wen", "A despensa do velho Wen", "Le garde-manger du vieux Wen", "Der Vorrat des alten Wen", "ウェン老の食料庫", "웬 노인의 식료품", "老温的食柜"),
    L("Wen trades recipes for ingredients: something hot, something cold and something sweet.", "Wen cambia recetas por ingredientes: algo picante, algo frío y algo dulce.", "Wen troca receitas por ingredientes: algo quente, algo frio e algo doce.", "Wen échange des recettes contre des ingrédients : du chaud, du froid, du sucré.", "Wen tauscht Rezepte gegen Zutaten: etwas Heißes, etwas Kaltes, etwas Süßes.", "ウェンは材料と引き換えに料理法を教える：熱いもの、冷たいもの、甘いもの。", "웬은 재료를 받고 요리법을 준다: 뜨거운 것, 차가운 것, 단 것.", "老温拿食谱换食材：一样辣的、一样凉的、一样甜的。"),
    [stage(obj("deliver", "NPC_HERMIT", T("QO_T_GIVE", "ITEM_EMBERROOT", "NAME_HERMIT"), item="emberroot", count=2),
           obj("deliver", "NPC_HERMIT", T("QO_T_GIVE", "ITEM_FROSTMINT", "NAME_HERMIT"), item="frostmint", count=2),
           obj("deliver", "NPC_HERMIT", T("QO_T_GIVE", "ITEM_HONEYCOMB", "NAME_HERMIT"), item="honeycomb", count=1),
           talk=[L("Good, good. Now listen closely, I only say recipes once.", "Bien, bien. Escucha, que las recetas solo las digo una vez.", "Bom, bom. Escute bem, só digo receita uma vez.", "Bien, bien. Écoutez, je ne dis les recettes qu'une fois.", "Gut, gut. Hör genau zu, Rezepte sage ich nur einmal.", "よし、よし。よく聞け、料理法は一度しか言わん。", "좋아, 좋아. 잘 들어, 요리법은 한 번만 말한다.", "好，好。听仔细了，方子我只说一遍。")])],
    {"recipes": [["emberroot", "raw_meat"], ["frostmint", "sunpear"], ["honeycomb", "sunpear", "sunpear"]], "jade": 1, "glimmer": 20},
    start="talk:NPC_HERMIT", requires=["sq_summit_offering"],
    offer_lines=[L("Two emberroots, two frostmints, one honeycomb. I'll pay in secrets of the pot.", "Dos raíces ígneas, dos mentas heladas, un panal. Pago en secretos de la olla.", "Duas raízes-brasa, duas mentas-geladas, um favo. Pago em segredos da panela.", "Deux racines-braise, deux menthes-givre, un rayon. Je paie en secrets de marmite.", "Zwei Glutwurzen, zwei Frostminzen, eine Wabe. Ich zahle in Topfgeheimnissen.", "熾根二つ、霜ミント二つ、蜂の巣一つ。鍋の秘伝で払おう。", "불씨뿌리 둘, 서리박하 둘, 벌집 하나. 냄비의 비법으로 갚지.", "两根烬根、两把霜薄荷、一块蜂巢。我拿锅里的秘诀来换。")]))
