"""Coast & sea quests (phase 4). Few, and each one teaches or ties systems
together: currents + tides + night (First Crossing), wreck entrances + the
lever/gate (The Ship That Never Returned), cooking + diving + vents (Under
the Keel), storms + the reef + storm rays (Storm Night), tides + a castaway's
story (The Vanishing Isle). Every place is reachable
by swimming with a current, gliding from Vigil Rock, or walking a low-tide
bar (docs/COAST_AND_SEA.md).
Most of the sea stays outside the journal: see seas.DISCOVERIES."""
from qdsl import L, T, quest, stage, obj

QUESTS = []
Q = QUESTS.append

LIGHT = [150, 1000]
PROMISE = [30, 1250]
LEVIATHAN = [720, 1260]
REEF = [560, 1020]
BAR = [320, 1280]

# --- First Crossing: the current, the light, the night -----------------------------------------------
Q(quest("sq_sea_first_crossing", "side", "exploration", "coast", 2, "medium",
    L("First Crossing", "Primera travesía", "Primeira travessia", "Première traversée", "Die erste Überfahrt", "はじめての渡海", "첫 항해", "初次渡海"),
    L("Sabel says the Tidewarden Light has been dark for years. The Gull Current runs straight to it, if you trust the sea.", "Sabel dice que el Faro del Guardamareas lleva años apagado. La Corriente de la Gaviota va directa hasta él, si confías en el mar.", "Sabel diz que o Farol do Guarda-Marés está apagado há anos. A Corrente da Gaivota vai direto até ele, se você confiar no mar.", "Sabel dit que le phare du Gardien des marées est éteint depuis des années. Le courant de la Mouette y mène tout droit, si l'on se fie à la mer.", "Sabel sagt, der Gezeitenwacht-Leuchtturm sei seit Jahren dunkel. Die Möwenströmung führt direkt hin, wenn man dem Meer traut.", "サベルいわく、潮守りの灯台は何年も消えたまま。鴎の潮流に身を任せれば、まっすぐ着くという。", "사벨은 조수지기 등대가 몇 년째 꺼져 있다고 한다. 바다를 믿는다면 갈매기 해류가 곧장 데려다준다.", "萨贝尔说守潮灯塔已经黑了好些年。信得过海的话，鸥流会直接把你送过去。"),
    [stage(obj("talk", "NPC_TIDEKEEPER", T("QO_T_TALK", "NAME_TIDEKEEPER")),
           talk=[L("See the foam line going south? That's the Gull Current. Swim into it and it swims for you. Coming back, take the one by the rocks.", "¿Ves la línea de espuma hacia el sur? Es la Corriente de la Gaviota. Métete y nadará por ti. Para volver, toma la de las rocas.", "Vê a linha de espuma indo para o sul? É a Corrente da Gaivota. Entre nela e ela nada por você. Na volta, pegue a das rochas.", "Tu vois la ligne d'écume vers le sud ? C'est le courant de la Mouette. Entres-y, il nage pour toi. Pour revenir, prends celui près des rochers.", "Siehst du die Schaumlinie nach Süden? Das ist die Möwenströmung. Schwimm hinein, dann schwimmt sie für dich. Zurück nimmst du die bei den Felsen.", "南へ延びる泡の筋が見えるか。鴎の潮流だ。入れば代わりに泳いでくれる。帰りは岩場のほうの流れに乗れ。", "남쪽으로 뻗은 거품 줄 보이지? 갈매기 해류야. 들어가면 대신 헤엄쳐 줘. 돌아올 땐 바위 쪽 해류를 타.", "看见往南的那道白沫了吗？那就是鸥流。游进去，它会替你游。回来时走礁石边那条。")]),
     stage(obj("discover", "tidewarden_light", T("QO_T_FIND", "POI_TIDEWARDEN_LIGHT"), marker=LIGHT),
           hint=[L("The foam line south of the Dawn wreck is the current. Rest on the rocks if you tire.", "La línea de espuma al sur del naufragio del Alba es la corriente. Descansa en las rocas si te cansas.", "A linha de espuma ao sul do naufrágio da Aurora é a corrente. Descanse nas rochas se cansar.", "La ligne d'écume au sud de l'épave de l'Aube, c'est le courant. Repose-toi sur les rochers si tu fatigues.", "Die Schaumlinie südlich des Morgenwracks ist die Strömung. Ruh dich auf den Felsen aus, wenn du müde wirst.", "暁の難破船の南の泡の筋が潮流だ。疲れたら岩で休め。", "새벽 난파선 남쪽의 거품 줄이 해류다. 지치면 바위에서 쉬어라.", "黎明沉船南边那道白沫就是海流。累了就在礁石上歇歇。")]),
     stage(obj("flag", "lighthouse_lit", T("QO_T_LIGHT", "POI_TIDEWARDEN_LIGHT"), marker=LIGHT),
           hint=[L("The lamp only takes a flame after dark.", "El farol solo prende después del anochecer.", "A lanterna só acende depois de escurecer.", "La lampe ne prend la flamme qu'à la nuit.", "Die Lampe nimmt erst nach Einbruch der Dunkelheit Feuer an.", "灯は日が暮れてからでないと点かない。", "등불은 해가 진 뒤에야 켜진다.", "灯只在天黑后才点得着。")]),
     stage(obj("talk", "NPC_TIDEKEEPER", T("QO_T_RETURN", "NAME_TIDEKEEPER")),
           talk=[L("I saw it from here. Keep that chart: the light shows you what's out there. The rest you find with your own eyes.", "Lo vi desde aquí. Guarda esa carta: el faro te muestra lo que hay allá fuera. El resto lo encuentras con tus ojos.", "Eu vi daqui. Guarde essa carta: o farol mostra o que há lá fora. O resto você acha com os próprios olhos.", "Je l'ai vu d'ici. Garde cette carte : le phare te montre ce qu'il y a au large. Le reste, tu le trouveras de tes yeux.", "Ich hab's von hier gesehen. Behalt die Karte: Das Licht zeigt dir, was da draußen ist. Den Rest findest du mit eigenen Augen.", "ここから見えたよ。その海図は取っておけ。灯が沖にあるものを示す。残りは自分の目で探せ。", "여기서 봤어. 그 해도는 간직해. 등대가 바깥에 뭐가 있는지 보여 줄 거야. 나머진 네 눈으로 찾아.", "我在这儿看见了。那张海图留着：灯塔会告诉你外面有什么，剩下的得靠你自己的眼睛。")])],
    {"glimmer": 40, "items": [{"id": "deepwater_broth", "count": 2}]},
    start="talk:NPC_TIDEKEEPER",
    offer_lines=[L("That light out there kept ships off the shoals. Dark for years now. Fancy a swim?", "Ese faro de allá mantenía a los barcos lejos de los bajíos. Lleva años apagado. ¿Te apetece nadar?", "Aquele farol mantinha os navios longe dos baixios. Apagado há anos. Topa nadar?", "Ce phare-là tenait les navires loin des hauts-fonds. Éteint depuis des années. Une petite nage ?", "Das Licht da draußen hielt Schiffe von den Untiefen fern. Seit Jahren dunkel. Lust auf ein Bad?", "あの灯台は船を浅瀬から守っていた。もう何年も消えている。泳いでみるか？", "저 등대가 배들을 여울에서 지켜 줬지. 몇 년째 꺼져 있어. 헤엄 좀 쳐 볼래?", "那座灯塔以前让船避开浅滩，黑了好些年了。想游一趟吗？")]))

# --- The Ship That Never Returned: three ways into a wreck -------------------------------------------
Q(quest("sq_sea_gulls_promise", "side", "exploration", "coast", 3, "medium",
    L("The Ship That Never Returned", "El barco que no regresó", "O navio que não voltou", "Le navire qui ne revint pas", "Das Schiff, das nie zurückkam", "帰らなかった船", "돌아오지 않은 배", "未归之船"),
    L("The Gull's Promise sailed the night the light went out. Sabel's brother was aboard. She wants to know what he wrote last.", "La Promesa de la Gaviota zarpó la noche en que se apagó el faro. El hermano de Sabel iba a bordo. Ella quiere saber qué escribió al final.", "A Promessa da Gaivota zarpou na noite em que o farol apagou. O irmão de Sabel estava a bordo. Ela quer saber o que ele escreveu por último.", "La Promesse de la Mouette a appareillé la nuit où le phare s'est éteint. Le frère de Sabel était à bord. Elle veut savoir ce qu'il a écrit en dernier.", "Das Möwenversprechen lief in der Nacht aus, als das Licht erlosch. Sabels Bruder war an Bord. Sie will wissen, was er zuletzt schrieb.", "灯が消えた夜に出航した鴎の約束号。サベルの兄が乗っていた。彼女は兄が最後に何を書いたか知りたい。", "등대가 꺼진 밤 출항한 갈매기의 약속호. 사벨의 오빠가 타고 있었다. 그녀는 그가 마지막으로 무엇을 적었는지 알고 싶어 한다.", "灯灭的那晚，鸥之诺号出了海，萨贝尔的哥哥就在船上。她想知道他最后写了什么。"),
    [stage(obj("discover", "gulls_promise", T("QO_T_FIND", "POI_GULLS_PROMISE"), marker=PROMISE),
           hint=[L("From Vigil Rock's top you can glide onto her deck. Or swim in through the breach.", "Desde lo alto del Islote del Vigía puedes planear hasta su cubierta. O entrar nadando por la brecha.", "Do alto do Rochedo do Vigia dá para planar até o convés. Ou entrar nadando pela brecha.", "Du haut du Rocher de la Vigie, tu peux planer jusqu'au pont. Ou entrer à la nage par la brèche.", "Vom Wachtfels aus kannst du auf ihr Deck gleiten. Oder durchs Leck hineinschwimmen.", "見張り岩の上から甲板へ滑空できる。あるいは破口から泳いで入れ。", "망루 바위 꼭대기에서 갑판으로 활공할 수 있다. 아니면 파공으로 헤엄쳐 들어가라.", "从望哨礁顶上可以滑翔到甲板，或者从破口游进去。")]),
     stage(obj("flag", "gulls_cabin_open", T("QO_T_USE", L("the lever in the hold", "la palanca de la bodega", "a alavanca do porão", "le levier de la cale", "den Hebel im Laderaum", "船倉のレバー", "선창의 레버", "船舱里的拉杆")), marker=PROMISE),
           hint=[L("The captain's door is jammed from the other side. Something in the hold still moves it.", "La puerta del capitán está atascada desde el otro lado. Algo en la bodega aún la mueve.", "A porta do capitão está emperrada do outro lado. Algo no porão ainda a move.", "La porte du capitaine est bloquée de l'autre côté. Quelque chose dans la cale la fait encore bouger.", "Die Kapitänstür klemmt von der anderen Seite. Etwas im Laderaum bewegt sie noch.", "船長室の扉は向こう側で詰まっている。船倉の何かでまだ動かせる。", "선장실 문이 저쪽에서 막혔다. 선창의 무언가가 아직 그걸 움직인다.", "船长室的门从另一边卡住了，船舱里有东西还能拉动它。")]),
     stage(obj("collect", "gulls_log", T("QO_T_TAKE", "ITEM_GULLS_LOG"), count=1, marker=PROMISE)),
     stage(obj("deliver", "NPC_TIDEKEEPER", T("QO_T_GIVE", "ITEM_GULLS_LOG", "NAME_TIDEKEEPER"), item="gulls_log"),
           talk=[L("\"Steering by the Vigil.\" He trusted the rock because the light was dark. Thank you. Now I know where to leave flowers.", "\"Rumbo por el Vigía.\" Confió en la roca porque el faro estaba apagado. Gracias. Ahora sé dónde dejar flores.", "\"Rumo pelo Vigia.\" Ele confiou na rocha porque o farol estava apagado. Obrigada. Agora sei onde deixar flores.", "« Cap sur la Vigie. » Il s'est fié au rocher parce que le phare était éteint. Merci. Je sais maintenant où laisser des fleurs.", "„Kurs auf den Wachtfels.“ Er vertraute dem Felsen, weil das Licht dunkel war. Danke. Jetzt weiß ich, wo ich Blumen hinlege.", "「見張り岩を目印に」。灯が消えていたから岩を信じたんだ。ありがとう。花を手向ける場所がわかった。", "\"망루를 보고 항해 중.\" 등대가 꺼져서 바위를 믿었던 거야. 고마워. 이제 어디에 꽃을 둘지 알겠어.", "“以望哨礁定向。”灯灭了，他只能信那块礁石。谢谢你，现在我知道该把花放在哪儿了。")])],
    {"glimmer": 70, "jade": 2, "items": [{"id": "lake_pearl", "count": 1}]},
    start="talk:NPC_TIDEKEEPER", requires=["sq_sea_first_crossing"],
    offer_lines=[L("With the light burning I can see the shoal again. And the mast that's stood on it since that night.", "Con el faro encendido vuelvo a ver el bajío. Y el mástil que está ahí desde aquella noche.", "Com o farol aceso vejo o baixio de novo. E o mastro que está ali desde aquela noite.", "Avec le phare allumé, je revois le haut-fond. Et le mât qui s'y dresse depuis cette nuit-là.", "Mit brennendem Licht sehe ich die Untiefe wieder. Und den Mast, der seit jener Nacht dort steht.", "灯が点いて、また浅瀬が見える。あの夜から立ったままの帆柱も。", "등대가 켜지니 여울이 다시 보여. 그날 밤부터 서 있는 돛대도.", "灯亮了，我又能看见那片浅滩，还有那晚之后一直立在那儿的桅杆。")]))

# --- Under the Keel: a broth for long breath, a deep wreck, a jammed door ----------------------------
Q(quest("sq_sea_under_keel", "side", "exploration", "coast", 4, "long",
    L("Under the Keel", "Bajo la quilla", "Sob a quilha", "Sous la quille", "Unter dem Kiel", "竜骨の下で", "용골 아래", "龙骨之下"),
    L("The Iron Leviathan lies fifteen metres down, too deep for one breath. Sabel knows a broth for divers and a vent that still breathes in the hold.", "El Leviatán de Hierro yace a quince metros, demasiado hondo para un solo aliento. Sabel conoce un caldo para buzos y un respiradero que aún respira en la bodega.", "O Leviatã de Ferro jaz a quinze metros, fundo demais para um só fôlego. Sabel conhece um caldo para mergulhadores e um respiro que ainda sopra no porão.", "Le Léviathan de fer gît à quinze mètres, trop profond pour un seul souffle. Sabel connaît un bouillon de plongeur et un évent qui respire encore dans la cale.", "Der Eiserne Leviathan liegt fünfzehn Meter tief, zu tief für einen Atemzug. Sabel kennt eine Taucherbrühe und eine Luftquelle, die im Laderaum noch atmet.", "鉄の巨鯨号は水深十五メートル、一息では届かない。サベルは潜り手のスープと、船倉でまだ息づく気泡口を知っている。", "강철 리바이어던은 수심 15미터, 한 숨으로는 너무 깊다. 사벨은 잠수부의 수프와 선창에서 아직 숨 쉬는 공기구멍을 안다.", "铁鲸号沉在十五米深处，一口气下不去。萨贝尔知道一种潜水汤，还知道船舱里有个还在冒气的气眼。"),
    [stage(obj("cook", "deepwater_broth", T("QO_T_COOK", "ITEM_DEEPWATER_BROTH")),
           hint=[L("A bluewater runner, a lantern squid, a sprig of frostmint.", "Un corredor de altamar, un calamar farol y una ramita de menta helada.", "Um corredor-de-alto-mar, uma lula-lanterna e um raminho de menta gelada.", "Un coureur du large, un calmar lanterne, un brin de menthe givrée.", "Ein Hochseeläufer, ein Laternenkalmar, ein Zweig Frostminze.", "外洋の走り魚、灯りイカ、フロストミントをひと枝。", "먼바다 질주어, 등불 오징어, 서리박하 한 줄기.", "一条远洋奔鱼、一只灯乌贼、一枝霜薄荷。")]),
     stage(obj("flag", "leviathan_cabin_open", T("QO_T_USE", L("the lever in the Leviathan's hold", "la palanca de la bodega del Leviatán", "a alavanca do porão do Leviatã", "le levier de la cale du Léviathan", "den Hebel im Laderaum des Leviathans", "巨鯨号の船倉のレバー", "리바이어던 선창의 레버", "铁鲸号船舱里的拉杆")), marker=LEVIATHAN),
           hint=[L("Follow the broken mast down. Bubbles in the hold mean air.", "Sigue el mástil roto hacia abajo. Burbujas en la bodega significan aire.", "Siga o mastro quebrado para baixo. Bolhas no porão significam ar.", "Suis le mât brisé vers le fond. Des bulles dans la cale, c'est de l'air.", "Folge dem gebrochenen Mast nach unten. Blasen im Laderaum heißen Luft.", "折れた帆柱をたどって潜れ。船倉の泡は空気の印だ。", "부러진 돛대를 따라 내려가. 선창의 거품은 공기라는 뜻이야.", "顺着断桅往下。船舱里冒泡，就是有气。")]),
     stage(obj("open_chest", "iron_leviathan:captain", T("QO_T_OPEN", L("the Leviathan's strongbox", "el cofre del Leviatán", "o cofre do Leviatã", "le coffre du Léviathan", "die Schatulle des Leviathans", "巨鯨号の金庫", "리바이어던의 금고", "铁鲸号的保险箱")), marker=LEVIATHAN)),
     stage(obj("talk", "NPC_TIDEKEEPER", T("QO_T_RETURN", "NAME_TIDEKEEPER")),
           talk=[L("That mask was my father's make. With it you'll see the reef the way the fish do.", "Esa máscara la hizo mi padre. Con ella verás el arrecife como lo ven los peces.", "Essa máscara foi meu pai quem fez. Com ela você verá o recife como os peixes veem.", "Ce masque, c'est mon père qui l'a fait. Avec, tu verras le récif comme les poissons.", "Die Maske hat mein Vater gemacht. Damit siehst du das Riff wie die Fische.", "その面は父の作だ。それがあれば魚のように珊瑚礁を見られる。", "그 가면은 우리 아버지가 만든 거야. 그걸 쓰면 물고기처럼 산호초를 볼 수 있어.", "那面罩是我父亲做的。戴上它，你看礁石就像鱼看一样。")])],
    {"glimmer": 90, "jade": 3},
    start="talk:NPC_TIDEKEEPER", requires=["sq_sea_gulls_promise"],
    offer_lines=[L("There's a bigger wreck past the reef. Iron. Deep. Nobody's opened her strongbox, because nobody's come back up with breath to spare.", "Hay un naufragio mayor pasado el arrecife. De hierro. Hondo. Nadie ha abierto su cofre, porque nadie ha vuelto a subir con aliento de sobra.", "Há um naufrágio maior depois do recife. De ferro. Fundo. Ninguém abriu o cofre, porque ninguém voltou com fôlego sobrando.", "Il y a une plus grosse épave après le récif. En fer. Profonde. Personne n'a ouvert son coffre : personne n'est remonté avec du souffle à revendre.", "Hinter dem Riff liegt ein größeres Wrack. Eisern. Tief. Niemand hat ihre Schatulle geöffnet, weil keiner mit Luft übrig wieder hochkam.", "珊瑚礁の先にもっと大きな難破船がある。鉄で、深い。金庫を開けた者はいない。息を残して戻った者がいないからな。", "산호초 너머에 더 큰 난파선이 있어. 철로 된. 깊어. 아무도 금고를 못 열었지. 숨이 남은 채로 돌아온 사람이 없거든.", "礁石那边还有艘更大的沉船，铁的，很深。没人打开过它的保险箱，因为没人能留着气游回来。")]))

# --- Storm Night: the reef changes its rules ----------------------------------------------------------
Q(quest("sq_sea_storm_night", "side", "combat", "coast", 4, "medium",
    L("Storm Night", "La noche de la tormenta", "A noite da tempestade", "La nuit de la tempête", "Die Sturmnacht", "嵐の夜", "폭풍의 밤", "风暴之夜"),
    L("In fair weather the Crystal Reef is a garden. In a storm its spires drink lightning and grow stormglass. Sabel wants some, and knows what else comes with the storm.", "Con buen tiempo el Arrecife de Cristal es un jardín. En tormenta sus agujas beben rayos y crían vidrio de tormenta. Sabel quiere un poco, y sabe qué más trae la tormenta.", "Com tempo bom o Recife de Cristal é um jardim. Na tempestade suas agulhas bebem raios e criam vidro-de-tempestade. Sabel quer um pouco, e sabe o que mais vem com ela.", "Par beau temps, le récif de cristal est un jardin. Dans la tempête, ses aiguilles boivent la foudre et font pousser le verre d'orage. Sabel en veut, et sait ce qui vient avec.", "Bei gutem Wetter ist das Kristallriff ein Garten. Im Sturm trinken seine Nadeln Blitze und lassen Sturmglas wachsen. Sabel will welches, und weiß, was der Sturm noch bringt.", "晴れた日の水晶礁は庭だ。嵐になると尖塔が雷を飲み、嵐硝子を育てる。サベルはそれが欲しい。嵐が何を連れてくるかも知っている。", "맑은 날 수정 산호초는 정원이다. 폭풍이 오면 첨탑이 번개를 마시고 폭풍유리를 키운다. 사벨은 그걸 원하고, 폭풍이 또 무엇을 데려오는지도 안다.", "晴天里水晶礁是座花园；风暴一来，礁尖饮下雷电，长出风暴玻璃。萨贝尔想要一些，也知道风暴还会带来什么。"),
    [stage(obj("reach", "", T("QO_T_REACH", "DISC_SEA_CRYSTAL_REEF"), pos=REEF, radius=45.0, marker=REEF, conditions={"weather": ["storm"]}),
           hint=[L("Only in a storm. Keep off the spires that hum.", "Solo con tormenta. Aléjate de las agujas que zumban.", "Só na tempestade. Fique longe das agulhas que zumbem.", "Seulement par tempête. Éloigne-toi des aiguilles qui bourdonnent.", "Nur im Sturm. Halt dich von summenden Nadeln fern.", "嵐のときだけ。唸る尖塔には近づくな。", "폭풍 때만. 웅웅대는 첨탑은 피해.", "只在风暴时去。离嗡嗡响的礁尖远点。")]),
     stage(obj("survive", "sea_reef_storm", T("QO_T_SURVIVE", "DISC_SEA_CRYSTAL_REEF"), marker=REEF),
           spawns=[{"kind": "encounter", "id": "sea_reef_storm", "mode": "survive", "pos": REEF, "radius": 24, "duration": 60, "interval": 8, "max_alive": 4, "trigger_radius": 30, "element": "electric",
                    "banner": L("The reef wakes", "El arrecife despierta", "O recife desperta", "Le récif s'éveille", "Das Riff erwacht", "礁が目覚める", "산호초가 깨어난다", "礁石苏醒"),
                    "waves": [{"entity": "ENEMY_STORM_RAY", "count": 2, "dist": 18}, {"entity": "ENEMY_NEEDLEFIN", "count": 3, "dist": 10}]}]),
     stage(obj("collect", "storm_glass", T("QO_T_GATHER", "ITEM_STORM_GLASS"), count=3, marker=REEF),
           hint=[L("Stormglass forms on a spire's crown right after the strike. Be quick, and dry.", "El vidrio de tormenta se forma en la corona de la aguja justo tras el rayo. Sé rápido, y no estés mojado.", "O vidro-de-tempestade se forma na coroa da agulha logo após o raio. Seja rápido, e esteja seco.", "Le verre d'orage se forme au sommet de l'aiguille juste après la foudre. Sois vif, et sec.", "Sturmglas bildet sich direkt nach dem Einschlag auf der Nadelkrone. Sei schnell, und trocken.", "嵐硝子は落雷の直後に尖塔の頂にできる。素早く、濡れずに。", "폭풍유리는 번개가 친 직후 첨탑 꼭대기에 맺힌다. 빠르게, 젖지 말고.", "雷一劈下，礁尖顶上就会结出风暴玻璃。手要快，身子要干。")]),
     stage(obj("talk", "NPC_TIDEKEEPER", T("QO_T_RETURN", "NAME_TIDEKEEPER")),
           talk=[L("You came back from the reef in a storm. Most don't try twice. I'll line your hull with this: lightning slides off glass.", "Volviste del arrecife en plena tormenta. Casi nadie lo intenta dos veces. Forraré tu casco con esto: el rayo resbala sobre el vidrio.", "Você voltou do recife em plena tempestade. Quase ninguém tenta duas vezes. Vou forrar seu casco com isto: o raio escorrega no vidro.", "Tu es revenu du récif en pleine tempête. Peu essaient deux fois. Je vais en doubler ta coque : la foudre glisse sur le verre.", "Du kamst im Sturm vom Riff zurück. Die meisten versuchen es kein zweites Mal. Ich füttere deinen Rumpf damit aus: Blitze gleiten an Glas ab.", "嵐の中、礁から戻ってきたか。二度挑む者は少ない。これで船体を張ってやろう。雷は硝子を滑る。", "폭풍 속에 산호초에서 돌아왔구나. 두 번 하는 사람은 드물어. 이걸로 네 선체를 덧대 줄게. 번개는 유리에서 미끄러지거든.", "你在风暴里从礁石回来了，很少有人敢去第二次。我拿这个给你的船壳镶一层：雷打在玻璃上会滑走。")])],
    {"glimmer": 80, "jade": 2, "items": [{"id": "abyssal_pearl", "count": 1}]},
    start="talk:NPC_TIDEKEEPER", requires=["sq_sea_first_crossing"],
    offer_lines=[L("When the sky goes green over the reef, the spires start to sing. That's when the glass grows. And the rays come up to feed.", "Cuando el cielo se pone verde sobre el arrecife, las agujas empiezan a cantar. Entonces crece el vidrio. Y suben las rayas a comer.", "Quando o céu fica verde sobre o recife, as agulhas começam a cantar. É quando o vidro cresce. E as raias sobem para comer.", "Quand le ciel verdit sur le récif, les aiguilles se mettent à chanter. C'est là que pousse le verre. Et que les raies montent se nourrir.", "Wenn der Himmel über dem Riff grün wird, beginnen die Nadeln zu singen. Dann wächst das Glas. Und die Rochen steigen zum Fressen auf.", "礁の上の空が緑になると尖塔が歌い出す。そのとき硝子が育ち、エイが餌を求めて上がってくる。", "산호초 위 하늘이 초록으로 변하면 첨탑들이 노래하기 시작해. 그때 유리가 자라고, 가오리들이 먹으러 올라오지.", "礁石上空一发绿，礁尖就开始唱。那时玻璃在长，鳐鱼也浮上来觅食。")]))

# --- The Vanishing Isle: the tide opens the way ------------------------------------------------------
Q(quest("dq_sea_vanishing_isle", "discovery", "exploration", "coast", 3, "short",
    L("The Vanishing Isle", "La isla que desaparece", "A ilha que desaparece", "L'île qui disparaît", "Die verschwindende Insel", "消える島", "사라지는 섬", "消失的岛"),
    L("Maren's husband buried something on an island that is only there when the sea goes out.", "El marido de Maren enterró algo en una isla que solo está cuando el mar se retira.", "O marido de Maren enterrou algo numa ilha que só existe quando o mar recua.", "Le mari de Maren a enterré quelque chose sur une île qui n'existe qu'à marée basse.", "Marens Mann hat etwas auf einer Insel vergraben, die nur da ist, wenn das Meer zurückweicht.", "マレンの夫は、潮が引いたときにしか現れない島に何かを埋めた。", "마렌의 남편은 바다가 물러날 때만 나타나는 섬에 무언가를 묻었다.", "玛伦的丈夫在一座只有退潮时才会出现的岛上埋了东西。"),
    [stage(obj("reach", "", T("QO_T_REACH", "DISC_SEA_VANISHING_BAR"), pos=BAR, radius=30.0, marker=BAR, conditions={"tide": "low"}),
           hint=[L("Watch the tide, not the clock. Around midday and midnight the bar dries out.", "Mira la marea, no el reloj. Hacia mediodía y medianoche el banco se seca.", "Olhe a maré, não o relógio. Perto do meio-dia e da meia-noite o banco seca.", "Regarde la marée, pas l'horloge. Vers midi et minuit, le banc s'assèche.", "Achte auf die Gezeiten, nicht die Uhr. Gegen Mittag und Mitternacht fällt die Bank trocken.", "時計ではなく潮を見ろ。昼と真夜中ごろ、砂州が干上がる。", "시계 말고 조수를 봐. 정오와 자정 무렵 모래톱이 드러나.", "看潮，不看钟。中午和午夜前后，沙洲会露出来。")]),
     stage(obj("open_chest", "vanishing_bar:buried", T("QO_T_OPEN", L("what Tomas buried", "lo que enterró Tomás", "o que Tomás enterrou", "ce que Tomas a enterré", "was Tomas vergraben hat", "トマスが埋めたもの", "토마스가 묻은 것", "托马斯埋下的东西")), marker=BAR)),
     stage(obj("talk", "NPC_CASTAWAY", T("QO_T_RETURN", "NAME_CASTAWAY")),
           talk=[L("A pearl, and a ribbon he meant for me. He always said the sea gives back, if you wait for the tide.", "Una perla, y una cinta que era para mí. Siempre decía que el mar devuelve, si esperas la marea.", "Uma pérola, e uma fita que era para mim. Ele sempre dizia que o mar devolve, se você esperar a maré.", "Une perle, et un ruban qui m'était destiné. Il disait toujours que la mer rend, si l'on attend la marée.", "Eine Perle, und ein Band, das für mich gedacht war. Er sagte immer, das Meer gibt zurück, wenn man auf die Gezeiten wartet.", "真珠と、私にくれるはずだったリボン。潮を待てば海は返してくれる、とあの人はいつも言っていた。", "진주 하나, 그리고 나한테 주려던 리본. 조수를 기다리면 바다는 돌려준다고 늘 말했지.", "一颗珍珠，还有一条本想送我的丝带。他总说，只要等到潮水，海会还回来的。")])],
    {"glimmer": 50, "jade": 1},
    start="talk:NPC_CASTAWAY",
    offer_lines=[L("Tomas buried something out on the bar before the storm took him. I can't dig, not any more. Go when the sea is out.", "Tomás enterró algo en el banco antes de que la tormenta se lo llevara. Yo ya no puedo cavar. Ve cuando el mar se retire.", "Tomás enterrou algo no banco antes que a tempestade o levasse. Eu já não consigo cavar. Vá quando o mar recuar.", "Tomas a enterré quelque chose sur le banc avant que la tempête l'emporte. Je ne peux plus creuser. Vas-y quand la mer se retire.", "Tomas hat vor dem Sturm etwas auf der Sandbank vergraben. Ich kann nicht mehr graben. Geh, wenn das Meer draußen ist.", "嵐にさらわれる前に、トマスは砂州に何かを埋めた。私はもう掘れない。潮が引いたら行って。", "폭풍이 토마스를 데려가기 전에 모래톱에 뭔가를 묻었어. 난 이제 못 파. 바다가 물러나면 가 봐.", "风暴带走托马斯之前，他在沙洲上埋了东西。我挖不动了。等海退了你去吧。")]))
