"""Vantrel Works: the three premium vehicles. Each quest line hands over a
schematic and a drive core; the machine itself is restored at the Vantrel
Depot (garage bench) for materials and glimmer. Late, demanding content:
never on the critical path (docs/VEHICLES.md)."""
from qdsl import L, T, quest, stage, obj

QUESTS = []
Q = QUESTS.append

DEPOT = [1060, 460]

# --- Sparrow (light bike): climb the Needles, then fly the Vantrel test line --------------------------
NEEDLES_LINE = L("the Vantrel test line", "la línea de pruebas Vantrel", "a linha de testes Vantrel", "la ligne d'essai Vantrel", "die Vantrel-Teststrecke", "ヴァントレルの試験線", "반트렐 시험 코스", "凡特雷尔试验线")
Q(quest("vq_sparrow", "side", "exploration", "valley", 4, "long",
    L("A Sparrow on the Needles", "Un gorrión en las Agujas", "Um pardal nas Agulhas", "Un moineau sur les Aiguilles", "Ein Spatz auf den Nadeln", "針岩の雀", "바늘바위의 참새", "针岩上的雀"),
    L("Kest swears a silver machine sits on top of the tallest needle. Its makers tested it by jumping off.", "Kest jura que hay una máquina plateada en lo alto de la aguja más alta. Sus creadores la probaban saltando.", "Kest jura que há uma máquina prateada no alto da agulha mais alta. Os criadores a testavam saltando.", "Kest jure qu'une machine argentée trône au sommet de la plus haute aiguille. Ses créateurs la testaient en sautant.", "Kest schwört, auf der höchsten Nadel stehe eine silberne Maschine. Ihre Erbauer testeten sie mit Sprüngen.", "ケストは一番高い針岩の上に銀の機械があると言う。作り手は飛び降りて試したらしい。", "케스트는 가장 높은 바늘바위 꼭대기에 은빛 기계가 있다고 맹세한다. 만든 이들은 뛰어내리며 시험했다.", "凯丝特发誓最高的针岩顶上有台银色机器，造它的人是靠往下跳来试车的。"),
    [stage(obj("climb", "needles", T("QO_T_CLIMB", "POI_NEEDLES"), min_y=76.0, radius=80.0),
           talk=[L("A frame of worn silver, wheels black as pitch. The engine is gone, but the schematic is tucked under the seat.", "Un chasis de plata gastada, ruedas negras como la brea. Falta el motor, pero el esquema está bajo el asiento.", "Um chassi de prata gasta, rodas negras como piche. O motor sumiu, mas o esquema está sob o banco.", "Un cadre d'argent usé, des roues noires comme la poix. Plus de moteur, mais le schéma est sous la selle.", "Ein Rahmen aus abgenutztem Silber, Räder pechschwarz. Der Motor fehlt, doch der Bauplan steckt unterm Sitz.", "擦り切れた銀の車体、漆黒の車輪。エンジンは無いが、座席の下に設計図が。", "닳은 은빛 차체, 칠흑 같은 바퀴. 엔진은 없지만 좌석 밑에 설계도가 있다.", "磨旧的银色车架，漆黑的轮子。引擎没了，座下却塞着图纸。")]),
     stage(obj("course", "sparrow_line", T("QO_T_COURSE_PAR", NEEDLES_LINE, "26"), par=26.0),
           spawns=[{"kind": "course", "id": "sparrow_line", "mode": "glide", "absolute": True, "ring_radius": 4.2, "range": 400, "par": 26.0,
                    "banner": NEEDLES_LINE,
                    "rings": [[420, -212, 90.0], [445, -192, 83.0], [470, -172, 76.0], [495, -152, 69.0], [520, -132, 61.0], [545, -112, 51.0], [570, -94, 41.0], [592, -78, 31.0]]}],
           hint=[L("The notes say the core only wakes for someone who has flown the whole line fast.", "Las notas dicen que el núcleo solo despierta para quien vuela toda la línea deprisa.", "As notas dizem que o núcleo só desperta para quem voa toda a linha depressa.", "Les notes disent que le cœur ne s'éveille que pour qui vole toute la ligne vite.", "Laut Notizen erwacht der Kern nur für jemanden, der die ganze Strecke schnell fliegt.", "記述によれば、核は試験線を速く飛び切った者にだけ目覚める。", "메모에 따르면 핵은 코스 전체를 빨리 난 사람에게만 깨어난다.", "笔记说，只有飞完整条线且够快的人，才能唤醒驱动核。")]),
     stage(obj("talk", "NPC_CLIMBER", T("QO_T_RETURN", "NAME_CLIMBER")),
           talk=[L("You flew it! Take both pieces to the Vantrel Depot in the desert. That bench still works, they say.", "¡La volaste! Lleva las dos piezas al Depósito Vantrel del desierto. Dicen que ese banco aún funciona.", "Você voou! Leve as duas peças ao Depósito Vantrel no deserto. Dizem que a bancada ainda funciona.", "Tu l'as volée ! Porte les deux pièces au Dépôt Vantrel, dans le désert. L'établi marche encore, dit-on.", "Du bist sie geflogen! Bring beide Teile zum Vantrel-Depot in der Wüste. Die Werkbank soll noch gehen.", "飛び切ったね！二つとも砂漠のヴァントレル車庫へ。あの作業台はまだ動くらしい。", "해냈구나! 두 부품을 사막의 반트렐 차고로 가져가. 그 작업대는 아직 된대.", "你飞完了！把两件东西带去沙漠里的凡特雷尔车库，听说那张工作台还能用。")])],
    {"items": [{"id": "vantrel_plan_sparrow", "count": 1}, {"id": "sparrow_core", "count": 1}], "jade": 2},
    start="talk:NPC_CLIMBER", requires=["mq_heights_beacon"],
    offer_lines=[L("Up on the tallest needle there's a silver machine. I can't reach it. Maybe you can.", "En lo alto de la aguja más alta hay una máquina plateada. Yo no llego. Quizá tú sí.", "No alto da agulha mais alta há uma máquina prateada. Eu não alcanço. Talvez você.", "Tout en haut de la plus haute aiguille, il y a une machine argentée. Moi, je n'y arrive pas. Toi, peut-être.", "Oben auf der höchsten Nadel steht eine silberne Maschine. Ich komm nicht hin. Du vielleicht.", "一番高い針岩の上に銀の機械がある。私には届かない。君なら。", "가장 높은 바늘바위 위에 은빛 기계가 있어. 난 못 닿아. 넌 될지도.", "最高那根针岩顶上有台银色机器，我够不着，也许你行。")]))

# --- Longwake (heavy bike): hold the depot, open the sealed bay --------------------------------------
Q(quest("vq_longwake", "side", "combat", "desert", 5, "long",
    L("The Longwake Bay", "La nave del Longwake", "O galpão do Longwake", "La baie du Longwake", "Die Longwake-Halle", "ロングウェイクの格納庫", "롱웨이크 격납고", "长航号机库"),
    L("Tobb sold a map to a Vantrel depot in the deep desert. Something big is sealed in its last bay, and the dunes guard it.", "Tobb vendió un mapa de un depósito Vantrel en el desierto profundo. Algo grande está sellado en su última nave, y las dunas lo guardan.", "Tobb vendeu um mapa de um depósito Vantrel no deserto profundo. Algo grande está lacrado no último galpão, e as dunas o guardam.", "Tobb a vendu la carte d'un dépôt Vantrel au fond du désert. Quelque chose de grand dort dans la dernière baie, et les dunes veillent.", "Tobb verkaufte eine Karte zu einem Vantrel-Depot tief in der Wüste. In der letzten Halle ist etwas Großes versiegelt, und die Dünen wachen.", "トッブは砂漠の奥のヴァントレル車庫の地図を売った。最後の格納庫に大きな何かが封じられ、砂丘がそれを守る。", "톱은 깊은 사막의 반트렐 차고 지도를 팔았다. 마지막 격납고에 큰 무언가가 봉인되어 있고, 모래언덕이 그것을 지킨다.", "托布卖出了一张深漠中凡特雷尔车库的地图。最后一间机库里封着个大家伙，沙丘守着它。"),
    [stage(obj("discover", "vantrel_depot", T("QO_T_FIND", "POI_VANTREL_DEPOT"), marker=DEPOT)),
     stage(obj("survive", "vq_depot_hold", T("QO_T_SURVIVE", "POI_VANTREL_DEPOT"), marker=DEPOT),
           spawns=[{"kind": "encounter", "id": "vq_depot_hold", "mode": "survive", "pos": DEPOT, "radius": 20, "duration": 80, "interval": 7, "max_alive": 5, "trigger_radius": 18, "element": "sand",
                    "banner": L("The dunes wake", "Las dunas despiertan", "As dunas despertam", "Les dunes s'éveillent", "Die Dünen erwachen", "砂丘が目覚める", "모래언덕이 깨어난다", "沙丘苏醒"),
                    "waves": [{"entity": "ENEMY_SCUTTLER", "count": 3, "dist": 16}, {"entity": "ENEMY_BULWARK", "count": 1, "dist": 18}, {"entity": "ENEMY_SPITTER", "count": 2, "dist": 18}]}]),
     stage(obj("retrieve", "longwake_bay", T("QO_T_TAKE", L("the sealed bay's contents", "el contenido de la nave sellada", "o conteúdo do galpão lacrado", "le contenu de la baie scellée", "den Inhalt der versiegelten Halle", "封印された格納庫の中身", "봉인된 격납고의 내용물", "封存机库里的东西")), marker=DEPOT),
           spawns=[{"kind": "object", "id": "longwake_bay", "look": "relic", "pos": [1066, 468], "prompt": "PROMPT_TAKE", "element": "sand"}],
           talk=[L("Under the tarp: a long silver frame, low and wide, and a drive core still warm. The bench can bring it back.", "Bajo la lona: un chasis plateado largo, bajo y ancho, y un núcleo aún tibio. El banco puede devolverle la vida.", "Sob a lona: um chassi prateado longo, baixo e largo, e um núcleo ainda morno. A bancada pode trazê-lo de volta.", "Sous la bâche : un long cadre argenté, bas et large, et un cœur encore tiède. L'établi peut le ramener.", "Unter der Plane: ein langer, flacher, breiter Silberrahmen und ein noch warmer Kern. Die Werkbank kann ihn zurückholen.", "覆いの下に、低く幅広い長い銀の車体と、まだ温かい駆動核。作業台で蘇らせられる。", "덮개 아래: 길고 낮고 넓은 은빛 차체와 아직 따뜻한 구동 핵. 작업대로 되살릴 수 있다.", "油布下面：一副又长又低又宽的银色车架，驱动核还温着。工作台能让它重生。")])],
    {"items": [{"id": "vantrel_plan_longwake", "count": 1}, {"id": "longwake_core", "count": 1}], "jade": 3, "glimmer": 60},
    start="talk:NPC_CARAVAN", requires=["mq_glass_matriarch"],
    offer_lines=[L("I've a map nobody wants: a Vantrel depot, deep south. Machines faster than wind, they say. Scuttlers too.", "Tengo un mapa que nadie quiere: un depósito Vantrel, al sur profundo. Máquinas más rápidas que el viento, dicen. Y escarbadores.", "Tenho um mapa que ninguém quer: um depósito Vantrel, no sul profundo. Máquinas mais rápidas que o vento, dizem. E escavadores.", "J'ai une carte dont personne ne veut : un dépôt Vantrel, loin au sud. Des machines plus rapides que le vent, dit-on. Et des fouisseurs.", "Ich hab eine Karte, die keiner will: ein Vantrel-Depot, tief im Süden. Maschinen schneller als der Wind, heißt es. Und Scharrer.", "誰も欲しがらない地図がある。南の奥のヴァントレル車庫だ。風より速い機械があるとか。砂這いもな。", "아무도 원치 않는 지도가 있지. 깊은 남쪽의 반트렐 차고. 바람보다 빠른 기계가 있대. 모래기어도.", "我有张没人要的地图：南边深处的凡特雷尔车库。据说里面的机器比风还快，也有掘沙虫。")]))

# --- Bellhull (amphibious capsule): the drowned hull, the core the hush took ----------------------------
Q(quest("vq_bellhull", "side", "exploration", "lakeshore", 5, "long",
    L("The Drowned Bell", "La campana ahogada", "O sino afogado", "La cloche noyée", "Die versunkene Glocke", "沈んだ鐘", "가라앉은 종", "沉钟"),
    L("Ilo's net keeps snagging on something shaped like a bell at the bottom of the lake. It has a window.", "La red de Ilo se engancha en algo con forma de campana en el fondo del lago. Tiene una ventana.", "A rede do Ilo vive enroscando em algo em forma de sino no fundo do lago. Tem uma janela.", "Le filet d'Ilo s'accroche sans cesse à une chose en forme de cloche au fond du lac. Elle a une vitre.", "Ilos Netz verfängt sich ständig an etwas Glockenförmigem am Seegrund. Es hat ein Fenster.", "イロの網が湖底の鐘の形をした物に引っかかる。窓がついている。", "일로의 그물이 호수 바닥의 종 모양 물체에 자꾸 걸린다. 창이 달려 있다.", "伊洛的网老是挂住湖底一个钟形的东西。它还有扇窗。"),
    [stage(obj("swim", "", T("QO_T_SWIM", L("the net's snag", "el enganche de la red", "o enrosco da rede", "l'accroc du filet", "die Stelle, an der das Netz hängt", "網の引っかかり", "그물이 걸린 곳", "挂网的地方")), marker=[-380, 30], pos=[-380, 30], radius=9.0),
           talk=[L("Through the black window: an empty seat, a folded wheel, and a hollow where the core should be. Scratched on the glass: \"taken to the hush\".", "Tras la ventana negra: un asiento vacío, una rueda plegada y un hueco donde debería estar el núcleo. Rayado en el cristal: \"llevado al silencio\".", "Pela janela negra: um assento vazio, uma roda dobrada e um vão onde deveria estar o núcleo. Riscado no vidro: \"levado ao silêncio\".", "Derrière la vitre noire : un siège vide, une roue repliée, un creux où devrait être le cœur. Gravé sur le verre : « emporté au silence ».", "Hinter dem schwarzen Fenster: ein leerer Sitz, ein eingeklapptes Rad, eine Mulde, wo der Kern sein sollte. Ins Glas geritzt: „in die Stille gebracht“.", "黒い窓の奥に、空の座席と畳まれた車輪、核があるはずの窪み。硝子に刻まれた文字：「静寂へ持ち去られた」。", "검은 창 너머: 빈 좌석, 접힌 바퀴, 핵이 있어야 할 빈자리. 유리에 긁힌 글씨: \"침묵으로 가져감\".", "黑窗后面：空座椅、折起的轮子，本该放驱动核的地方空着。玻璃上刻着：“带去了寂静之地”。")]),
     stage(obj("kill", "ENEMY_SHADE", T("QO_T_DEFEAT", "NAME_SHADE"), count=5, hint="area", area_radius=260.0, marker=[800, -760])),
     stage(obj("survive", "vq_bell_vigil", T("QO_T_SURVIVE", "POI_HOLLOW_RING"), marker=[1000, -790]),
           spawns=[{"kind": "encounter", "id": "vq_bell_vigil", "mode": "survive", "pos": [1000, -790], "radius": 18, "duration": 75, "interval": 7, "max_alive": 5, "trigger_radius": 16, "element": "still",
                    "banner": L("The hush answers", "El silencio responde", "O silêncio responde", "Le silence répond", "Die Stille antwortet", "静寂が応える", "침묵이 응답한다", "寂静回应了"),
                    "waves": [{"entity": "ENEMY_SHADE", "count": 2, "dist": 15}, {"entity": "ENEMY_WISP", "count": 2, "dist": 15}]}]),
     stage(obj("talk", "NPC_FISHER", T("QO_T_RETURN", "NAME_FISHER")),
           talk=[L("The core, level as still water! Take the drawings too, I pulled them out of the hull. The depot in the desert can raise her.", "¡El núcleo, nivelado como agua quieta! Llévate también los planos, los saqué del casco. El depósito del desierto puede reflotarla.", "O núcleo, nivelado como água parada! Leve os desenhos também, tirei do casco. O depósito do deserto pode reerguê-la.", "Le cœur, de niveau comme l'eau calme ! Prends aussi les dessins, je les ai tirés de la coque. Le dépôt du désert peut la relever.", "Der Kern, waagrecht wie stilles Wasser! Nimm die Zeichnungen mit, ich hab sie aus dem Rumpf geholt. Das Depot in der Wüste kann sie heben.", "静かな水のように水平な核だ！図面も持っていけ、船体から引き上げた。砂漠の車庫なら蘇らせられる。", "잔잔한 물처럼 수평인 핵이군! 설계도도 가져가, 선체에서 건졌어. 사막의 차고라면 되살릴 수 있어.", "驱动核，平得像静水！图纸也拿去，是我从壳里捞出来的。沙漠里的车库能让它重新浮起来。")])],
    {"items": [{"id": "vantrel_plan_bellhull", "count": 1}, {"id": "bellhull_core", "count": 1}], "jade": 3, "glimmer": 60},
    start="talk:NPC_FISHER", requires=["mq_veil_edge"],
    offer_lines=[L("My net snags on a bell down there. A bell with a window. Will you swim out and look?", "Mi red se engancha en una campana allá abajo. Una campana con ventana. ¿Nadas a mirar?", "Minha rede enrosca num sino lá embaixo. Um sino com janela. Nada até lá para ver?", "Mon filet s'accroche à une cloche là-dessous. Une cloche avec une vitre. Tu vas voir à la nage ?", "Mein Netz hängt da unten an einer Glocke. Einer Glocke mit Fenster. Schwimmst du hin und schaust?", "網が湖底の鐘に引っかかる。窓のある鐘だ。泳いで見てきてくれるか。", "그물이 저 아래 종에 걸려. 창 달린 종이야. 헤엄쳐 가서 봐 줄래?", "我的网挂在下面一口钟上，一口带窗的钟。你游过去看看？")]))
