"""The Veil Reaches: echoes that only speak at night, resonant crystals, a
pilgrim escort through the hush and the Hollow Shade."""
from qdsl import L, T, quest, stage, obj

QUESTS = []
Q = QUESTS.append

ECHO = L("the Warden echoes", "los ecos de los Guardianes", "os ecos dos Guardiões", "les échos des Gardiens", "die Hüterechos", "守り人の残響", "지기의 메아리", "守风者回响")
Q(quest("dq_veil_echoes", "discovery", "exploration", "veil", 3, "medium",
    L("Echoes of the Wardens", "Ecos de los Guardianes", "Ecos dos Guardiões", "Échos des Gardiens", "Echos der Hüter", "守り人の残響", "지기의 메아리", "守风者的回响"),
    L("At night, pale stones on the Veil's rim repeat the last words of the Wardens who fell here.", "De noche, piedras pálidas en el borde del Velo repiten las últimas palabras de los Guardianes caídos.", "À noite, pedras pálidas na borda do Véu repetem as últimas palavras dos Guardiões caídos.", "La nuit, des pierres pâles au bord du Voile répètent les derniers mots des Gardiens tombés ici.", "Nachts wiederholen fahle Steine am Schleierrand die letzten Worte der hier gefallenen Hüter.", "夜、帳の縁の白い石が、ここで倒れた守り人の最期の言葉を繰り返す。", "밤이면 장막 가장자리의 창백한 돌들이 이곳에서 쓰러진 지기들의 마지막 말을 되뇐다.", "夜里，帷幕边缘的苍白石头复述着殒落于此的守风者遗言。"),
    [stage(obj("interact", "group:veil_echo", T("QO_T_NIGHT", L("Listen to the Warden echoes", "Escucha los ecos de los Guardianes", "Ouça os ecos dos Guardiões", "Écoutez les échos des Gardiens", "Lausche den Hüterechos", "守り人の残響を聞く", "지기의 메아리 듣기", "聆听守风者回响")), count=5, conditions={"period": "night"}, hint="area", area_radius=230.0, marker=[880, -880]))],
    {"cosmetic": "echo_veil", "jade": 2, "items": [{"id": "vital_seed", "count": 1}]},
    start="event",
    spawns=[{"kind": "object", "id": "veil_echo_%d" % i, "group": "veil_echo", "look": "stone", "pos": p, "when": "open", "conditions": {"period": "night"}, "prompt": "PROMPT_EXAMINE",
             "element": "still", "hint_key": "HINT_WRONG_TIME", "range": 220, "hide_used": False, "lines": [ln]}
            for i, (p, ln) in enumerate([
                ([1001, -792], L("\"Hold the line. The fires will come.\"", "\"Resistid. Los fuegos llegarán.\"", "\"Aguentem. Os fogos virão.\"", "« Tenez la ligne. Les feux viendront. »", "„Haltet die Linie. Die Feuer werden kommen.“", "「持ちこたえろ。火は来る」", "\"버텨라. 불은 온다.\"", "“守住，火会来的。”")),
                ([834, -1023], L("\"It doesn't hate us. It just wants everything to stop.\"", "\"No nos odia. Solo quiere que todo se detenga.\"", "\"Não nos odeia. Só quer que tudo pare.\"", "« Il ne nous hait pas. Il veut juste que tout s'arrête. »", "„Es hasst uns nicht. Es will nur, dass alles aufhört.“", "「憎んではいない。すべてを止めたいだけだ」", "\"우릴 미워하는 게 아냐. 모든 게 멈추길 바랄 뿐.\"", "“它不恨我们，它只想让一切停下。”")),
                ([926, -1023], L("\"Tell my apprentice the Vela was always theirs.\"", "\"Decidle a mi aprendiz que la Vela siempre fue suya.\"", "\"Digam ao meu aprendiz que a Vela sempre foi dele.\"", "« Dites à mon apprenti que la Vela a toujours été à lui. »", "„Sagt meinem Lehrling, die Vela gehörte immer ihm.“", "「弟子に伝えてくれ。ヴェラはずっとお前のものだったと」", "\"내 견습생에게 전해라. 벨라는 늘 네 것이었다고.\"", "“告诉我的徒弟，风帆一直是他的。”")),
                ([760, -760], L("\"Three anchors. Break them and the isles will rise.\"", "\"Tres anclas. Rompedlas y las islas se alzarán.\"", "\"Três âncoras. Quebrem-nas e as ilhas subirão.\"", "« Trois ancres. Brisez-les et les îles s'élèveront. »", "„Drei Anker. Brecht sie, und die Inseln steigen.“", "「錨は三つ。壊せば島々が昇る」", "\"닻은 셋. 부수면 섬들이 떠오른다.\"", "“三座锚，毁掉它们，浮岛就会升起。”")),
                ([1030, -880], L("\"The wind remembers every one of us.\"", "\"El viento nos recuerda a todos.\"", "\"O vento se lembra de cada um de nós.\"", "« Le vent se souvient de chacun de nous. »", "„Der Wind erinnert sich an jeden von uns.“", "「風は我ら一人一人を覚えている」", "\"바람은 우리 하나하나를 기억한다.\"", "“风记得我们每一个人。”"))])]))

Q(quest("sq_crystal_resonance", "side", "gathering", "veil", 3, "medium",
    L("Crystal Resonance", "Resonancia de cristal", "Ressonância de cristal", "Résonance cristalline", "Kristallresonanz", "結晶の共鳴", "수정의 공명", "晶石共鸣"),
    L("Sister Maru believes the still crystals can be tuned to push the hush back from her camp.", "La hermana Maru cree que los cristales quietos pueden afinarse para alejar el silencio de su campamento.", "Irmã Maru acredita que os cristais quietos podem ser afinados para afastar o silêncio do acampamento.", "Sœur Maru pense qu'on peut accorder les cristaux immobiles pour repousser le silence de son camp.", "Schwester Maru glaubt, die Stillkristalle ließen sich stimmen, um die Stille vom Lager fernzuhalten.", "マル修道女は、静晶を調律すれば野営地から静寂を押し返せると信じている。", "마루 수녀는 고요 수정을 조율하면 야영지에서 침묵을 밀어낼 수 있다고 믿는다.", "玛露修女相信调和静晶能把寂静从营地推开。"),
    [stage(obj("gather", "still_crystal", T("QO_T_GATHER", L("still crystals", "cristales quietos", "cristais quietos", "cristaux immobiles", "Stillkristalle", "静晶", "고요 수정", "静晶")), count=3, hint="area", area_radius=220.0, marker=[880, -880])),
     stage(obj("talk", "NPC_PILGRIM", T("QO_T_RETURN", "NAME_PILGRIM")),
           talk=[L("Hear that? A clear note. The hush steps back. Bless you, wind-walker.", "¿Lo oyes? Una nota clara. El silencio retrocede. Bendito seas, caminante del viento.", "Ouviu? Uma nota clara. O silêncio recua. Abençoado seja, andarilho do vento.", "Vous entendez ? Une note claire. Le silence recule. Soyez béni, marcheur du vent.", "Hörst du? Ein klarer Ton. Die Stille weicht. Gesegnet seist du, Windgänger.", "聞こえる？澄んだ音。静寂が退く。風を歩く人に祝福を。", "들리니? 맑은 소리. 침묵이 물러난다. 바람을 걷는 이여, 축복을.", "听见了吗？清亮的一声，寂静退了。愿风护佑你，行风者。")])],
    {"jade": 2, "items": [{"id": "vital_seed", "count": 1}], "glimmer": 40},
    start="talk:NPC_PILGRIM", requires=["mq_veil_edge"],
    offer_lines=[L("Three still crystals, and I can tune a bell that keeps the hush away. Will you gather them?", "Tres cristales quietos, y podré afinar una campana que aleje el silencio. ¿Los recoges?", "Três cristais quietos, e posso afinar um sino que afasta o silêncio. Você os colhe?", "Trois cristaux immobiles, et j'accorderai une cloche qui tient le silence au loin. Vous les récoltez ?", "Drei Stillkristalle, und ich stimme eine Glocke, die die Stille fernhält. Sammelst du sie?", "静晶が三つあれば、静寂を遠ざける鐘を調律できる。集めてくれる？", "고요 수정 셋이면 침묵을 막는 종을 조율할 수 있어. 모아 줄래?", "三块静晶，我就能调一口驱散寂静的钟。你去采吗？")]))

Q(quest("sq_pilgrim_path", "side", "npc", "veil", 3, "short",
    L("The Pilgrims' Path", "El camino de los peregrinos", "O caminho dos peregrinos", "Le chemin des pèlerins", "Der Pilgerpfad", "巡礼の道", "순례자의 길", "朝圣之路"),
    L("A pilgrim wants to pray at the Hushed Shrine. Shades wait along the way.", "Un peregrino quiere rezar en el Santuario silente. Las sombras esperan en el camino.", "Um peregrino quer rezar no Santuário silente. Sombras esperam no caminho.", "Un pèlerin veut prier au Sanctuaire muet. Des ombres guettent en chemin.", "Ein Pilger will am Stillen Schrein beten. Schatten lauern am Weg.", "巡礼者が静寂の祠で祈りたい。道には影が待つ。", "순례자가 침묵의 사당에서 기도하고 싶어 한다. 길에는 그림자가 기다린다.", "一位朝圣者想去寂静神祠祈祷，沿途有暗影埋伏。"),
    [stage(obj("escort", "pilgrim_walk", T("QO_T_ESCORT", L("the pilgrim", "al peregrino", "o peregrino", "le pèlerin", "den Pilger", "巡礼者", "순례자", "朝圣者")), marker=[656, -646]))],
    {"jade": 2, "items": [{"id": "mending_tea", "count": 2}]},
    start="talk:NPC_PILGRIM", requires=["mq_veil_edge"],
    spawns=[{"kind": "encounter", "id": "pilgrim_walk", "mode": "escort", "pos": [656, -646], "actor": "NPC_TRAVELER", "actor_hp": 110, "when": "active", "element": "still", "vanish": True,
             "path": [[664, -664], [676, -684], [688, -702], [697, -716]], "wait_distance": 20,
             "ambushes": [{"at": 1, "entity": "ENEMY_SHADE", "count": 2, "dist": 12}, {"at": 3, "entity": "ENEMY_WISP", "count": 2, "dist": 10}],
             "start_lines": [L("I'm ready. Walk ahead; I'll pray as we go.", "Estoy listo. Ve delante; rezaré por el camino.", "Estou pronto. Vá na frente; rezarei no caminho.", "Je suis prêt. Marchez devant, je prierai en chemin.", "Ich bin bereit. Geh voran, ich bete unterwegs.", "準備はいい。先に歩いて、祈りながら行く。", "준비됐어. 앞장서, 가면서 기도할게.", "我准备好了。你在前面走，我边走边祷告。")],
             "end_lines": [L("The shrine. Thank you. I'll stay and keep the lamp.", "El santuario. Gracias. Me quedaré a cuidar la lámpara.", "O santuário. Obrigado. Ficarei cuidando da lâmpada.", "Le sanctuaire. Merci. Je resterai veiller la lampe.", "Der Schrein. Danke. Ich bleibe und hüte die Lampe.", "祠だ。ありがとう。ここで灯を守るよ。", "사당이다. 고마워. 남아서 등불을 지킬게.", "神祠到了，谢谢你。我留下守灯。")]}],
    offer_lines=[L("One of my pilgrims wants the Hushed Shrine. I can't leave the camp. Walk with him?", "Uno de mis peregrinos quiere ir al Santuario silente. No puedo dejar el campamento. ¿Lo acompañas?", "Um dos meus peregrinos quer ir ao Santuário silente. Não posso deixar o acampamento. Acompanha?", "Un de mes pèlerins veut aller au Sanctuaire muet. Je ne peux quitter le camp. Vous l'accompagnez ?", "Einer meiner Pilger will zum Stillen Schrein. Ich kann das Lager nicht verlassen. Begleitest du ihn?", "巡礼者の一人が静寂の祠へ行きたいと。私は離れられない。一緒に歩いてくれる？", "순례자 하나가 침묵의 사당에 가고 싶어 해. 난 야영지를 못 떠나. 함께 가 줄래?", "我有位朝圣者想去寂静神祠，我离不开营地。你陪他走一趟？")]))

Q(quest("sq_hollow_shade", "side", "boss", "veil", 4, "medium",
    L("The Hollow Shade", "La sombra hueca", "A sombra oca", "L'ombre creuse", "Der hohle Schatten", "虚ろな影", "텅 빈 그림자", "空洞之影"),
    L("A shade larger than the rest walks the Hollow Ring. Maru says it was a Warden once.", "Una sombra mayor que las demás recorre el Anillo hueco. Maru dice que una vez fue un Guardián.", "Uma sombra maior que as outras anda pelo Anel oco. Maru diz que já foi um Guardião.", "Une ombre plus grande que les autres arpente le Cercle creux. Maru dit que ce fut un Gardien.", "Ein größerer Schatten wandelt im Hohlen Ring. Maru sagt, er war einst ein Hüter.", "他より大きな影が虚ろの環を歩く。マルはかつて守り人だったと言う。", "다른 것보다 큰 그림자가 텅 빈 고리를 걷는다. 마루는 한때 지기였다고 한다.", "一道格外庞大的暗影在空洞之环徘徊。玛露说它曾是守风者。"),
    [stage(obj("boss", "BOSS_HOLLOW_SHADE", T("QO_T_DEFEAT", "NAME_HOLLOW_SHADE"), marker=[1000, -790])),
     stage(obj("talk", "NPC_PILGRIM", T("QO_T_RETURN", "NAME_PILGRIM")),
           talk=[L("Then they rest at last. Take their colour — it suits the dusk you walk in.", "Entonces por fin descansan. Toma su color; le va al crepúsculo por el que caminas.", "Então enfim descansam. Leve a cor deles; combina com o crepúsculo em que você anda.", "Alors ils reposent enfin. Prenez leur couleur — elle sied au crépuscule où vous marchez.", "Dann ruhen sie endlich. Nimm ihre Farbe — sie passt zur Dämmerung, in der du gehst.", "ならば、やっと眠れたのね。その色を。あなたの歩む黄昏に似合う。", "그럼 드디어 쉬겠구나. 그들의 빛깔을 가져가, 네가 걷는 황혼에 어울려.", "那他们终于安息了。收下这抹颜色，配你走过的暮色。")])],
    {"cosmetic": "trail_dusk", "jade": 3, "glimmer": 60},
    start="talk:NPC_PILGRIM", requires=["mq_anchors"],
    offer_lines=[L("There's a great shade in the Hollow Ring. If it was a Warden, it deserves to rest.", "Hay una gran sombra en el Anillo hueco. Si fue un Guardián, merece descansar.", "Há uma grande sombra no Anel oco. Se foi um Guardião, merece descansar.", "Une grande ombre hante le Cercle creux. Si ce fut un Gardien, il mérite le repos.", "Im Hohlen Ring wandelt ein großer Schatten. War er ein Hüter, verdient er Ruhe.", "虚ろの環に大きな影がいる。守り人だったなら、休ませてあげて。", "텅 빈 고리에 큰 그림자가 있어. 지기였다면 쉴 자격이 있지.", "空洞之环里有道巨影。若它曾是守风者，就该让它安息。")]))
