# Wind Warden landmarks, desert and Veil regions. Columns: en, es, pt, fr, de, ja, ko, zh
WORLD2 = {
    "POI_CLOUD_TEMPLE": ["Cloud Terrace Temple", "Templo de las Terrazas de Nube", "Templo dos Terraços de Nuvem", "Temple des Terrasses de Nuées", "Wolkenterrassen-Tempel", "雲台の寺", "구름 누대 사원", "云台寺"],
    "POI_WAYSIDE_SHRINE": ["Wayside Wind Shrine", "Santuario del Camino", "Santuário do Caminho", "Sanctuaire du Chemin", "Wegschrein", "道端の風祠", "길가의 바람 사당", "路旁风祠"],
    "POI_HEATH_SHRINE": ["Heath Wind Shrine", "Santuario del Brezo", "Santuário da Urze", "Sanctuaire de la Lande", "Heide-Windschrein", "ヒースの風祠", "히스 바람 사당", "石楠风祠"],
    "POI_JADE_BRIDGE": ["Jade Crossing", "Paso de Jade", "Passagem de Jade", "Passage de Jade", "Jadeübergang", "翡翠の渡し", "비취 다리", "翠渡桥"],
    "POI_SUNKEN_HALL": ["Sunken Hall", "Salón Hundido", "Salão Afundado", "Salle Engloutie", "Versunkene Halle", "沈んだ広間", "가라앉은 전각", "沉殿"],
    "LORE_TEMPLE": ["The Wind Wardens raised this court where the valley winds meet. Carved over the altar: 'We do not hold the wind. We give it somewhere to go.'", "Los Guardianes del Viento alzaron este patio donde se cruzan los vientos del valle. Tallado sobre el altar: «No retenemos el viento. Le damos un lugar adonde ir.»", "Os Guardiões do Vento ergueram este pátio onde os ventos do vale se encontram. Entalhado sobre o altar: «Não prendemos o vento. Damos a ele um lugar para ir.»", "Les Gardiens du Vent ont bâti cette cour où se croisent les vents de la vallée. Gravé sur l'autel : « Nous ne retenons pas le vent. Nous lui offrons un chemin. »", "Die Windhüter errichteten diesen Hof, wo sich die Talwinde treffen. Über dem Altar: „Wir halten den Wind nicht. Wir geben ihm einen Weg.“", "風守りは谷の風が出会う場所にこの庭を築いた。祭壇に刻まれた言葉――「風を捕らえはしない。行き先を与えるのだ」", "바람지기들은 골짜기 바람이 만나는 곳에 이 뜰을 세웠다. 제단 위 글귀: '우리는 바람을 붙잡지 않는다. 갈 곳을 내어줄 뿐.'", "守风人在谷风交汇之处筑起此庭。祭坛上刻着：“我们不囚风，只为它指一条去路。”"],
    "LORE_SHRINE": ["A wind stone. Travellers tie a ribbon here and ask for a kind road.", "Una piedra del viento. Los viajeros atan aquí una cinta y piden un buen camino.", "Uma pedra do vento. Viajantes amarram uma fita aqui e pedem um bom caminho.", "Une pierre du vent. Les voyageurs y nouent un ruban et demandent une route clémente.", "Ein Windstein. Reisende binden hier ein Band und bitten um einen guten Weg.", "風の石。旅人はここにリボンを結び、良い道を願う。", "바람의 돌. 나그네들은 여기 리본을 묶고 순탄한 길을 빈다.", "一块风石。旅人在此系上丝带，祈求一路平安。"],
    "LORE_BRIDGE": ["The crossing's keystone is carved with two currents that never touch.", "La clave del puente muestra dos corrientes que nunca se tocan.", "A pedra-chave da ponte mostra duas correntes que nunca se tocam.", "La clé de voûte montre deux courants qui ne se touchent jamais.", "Der Schlussstein zeigt zwei Strömungen, die sich nie berühren.", "要石には決して触れ合わない二つの流れが刻まれている。", "쐐기돌에는 결코 닿지 않는 두 물결이 새겨져 있다.", "拱心石上刻着两道永不相交的水流。"],
    "LORE_SUNKEN_HALL": ["Its roof slid into the earth in one night. The Wardens left, but their lanterns were never taken down.", "Su tejado se hundió en la tierra en una sola noche. Los Guardianes se fueron, pero nadie descolgó sus faroles.", "Seu telhado afundou na terra numa só noite. Os Guardiões partiram, mas ninguém tirou suas lanternas.", "Son toit a glissé dans la terre en une nuit. Les Gardiens sont partis, mais leurs lanternes sont restées.", "Sein Dach versank in einer Nacht in der Erde. Die Hüter gingen, doch ihre Laternen blieben hängen.", "屋根は一夜にして大地に沈んだ。風守りは去ったが、灯籠は下ろされなかった。", "지붕은 하룻밤 새 땅속으로 가라앉았다. 바람지기들은 떠났지만 등불은 아무도 내리지 않았다.", "屋顶在一夜之间沉入地下。守风人离去了，灯笼却从未被取下。"],
}
