# UI / system strings. Columns: en, es, pt, fr, de, ja, ko, zh
UI = {
    # Buttons (touch)
    "BTN_ATTACK": ["Attack", "Atacar", "Atacar", "Attaque", "Angriff", "攻撃", "공격", "攻击"],
    "BTN_JUMP": ["Jump", "Saltar", "Pular", "Saut", "Sprung", "ジャンプ", "점프", "跳跃"],
    "BTN_DODGE": ["Dodge", "Esquivar", "Esquivar", "Esquive", "Ausweichen", "回避", "회피", "闪避"],
    "BTN_INTERACT": ["Use", "Usar", "Usar", "Utiliser", "Benutzen", "使う", "사용", "使用"],
    "BTN_BLOCK": ["Guard", "Bloquear", "Bloquear", "Garde", "Blocken", "ガード", "방어", "格挡"],
    "BTN_LOCK": ["Lock", "Fijar", "Mirar", "Cibler", "Fixieren", "注目", "고정", "锁定"],
    "BTN_ITEM": ["Item", "Objeto", "Item", "Objet", "Item", "アイテム", "아이템", "道具"],
    "BTN_WEAPON": ["Swap", "Cambiar", "Trocar", "Changer", "Wechseln", "持替", "교체", "切换"],
    "BTN_DROP": ["Let go", "Soltar", "Soltar", "Lâcher", "Loslassen", "手を離す", "놓기", "松手"],
    "BTN_LEAP": ["Leap", "Impulso", "Impulso", "Bond", "Satz", "跳ぶ", "도약", "跃起"],
    "BTN_GLIDE": ["Vela", "Vela", "Vela", "Vela", "Vela", "ベラ", "벨라", "风帆"],
    "BTN_CLOSE": ["Fold", "Plegar", "Recolher", "Replier", "Einklappen", "たたむ", "접기", "收起"],
    "BTN_MAP": ["Map", "Mapa", "Mapa", "Carte", "Karte", "地図", "지도", "地图"],
    "BTN_BAG": ["Bag", "Bolsa", "Bolsa", "Sac", "Tasche", "持ち物", "가방", "背包"],
    "BTN_RESUME": ["Resume", "Continuar", "Continuar", "Reprendre", "Weiter", "再開", "계속", "继续"],
    "BTN_CLOSE_MENU": ["Close", "Cerrar", "Fechar", "Fermer", "Schließen", "閉じる", "닫기", "关闭"],
    # Prompts
    "PROMPT_USE": ["Use", "Usar", "Usar", "Utiliser", "Benutzen", "使う", "사용", "使用"],
    "PROMPT_GATHER": ["Gather", "Recoger", "Colher", "Cueillir", "Sammeln", "採る", "채집", "采集"],
    "PROMPT_OPEN": ["Open", "Abrir", "Abrir", "Ouvrir", "Öffnen", "開ける", "열기", "打开"],
    "PROMPT_CAMP": ["Camp", "Acampar", "Acampar", "Camp", "Lager", "野営", "야영", "扎营"],
    "PROMPT_READ": ["Read", "Leer", "Ler", "Lire", "Lesen", "読む", "읽기", "阅读"],
    "PROMPT_TALK": ["Talk", "Hablar", "Falar", "Parler", "Reden", "話す", "대화", "交谈"],
    # Tabs & menus
    "TAB_INVENTORY": ["Inventory", "Inventario", "Inventário", "Inventaire", "Inventar", "持ち物", "소지품", "物品"],
    "TAB_CRAFTING": ["Crafting", "Fabricar", "Criar", "Artisanat", "Herstellen", "クラフト", "제작", "制作"],
    "TAB_MAP": ["Map", "Mapa", "Mapa", "Carte", "Karte", "地図", "지도", "地图"],
    "TAB_SETTINGS": ["Settings", "Ajustes", "Ajustes", "Options", "Optionen", "設定", "설정", "设置"],
    "MENU_SUBTITLE": ["Every horizon is reachable.", "Todo horizonte es alcanzable.", "Todo horizonte é alcançável.", "Chaque horizon est à portée.", "Jeder Horizont ist erreichbar.", "すべての地平線へ。", "모든 지평선에 닿을 수 있다.", "每一道地平线都触手可及。"],
    "MENU_CONTINUE": ["Continue", "Continuar", "Continuar", "Continuer", "Fortsetzen", "つづきから", "이어하기", "继续游戏"],
    "MENU_NEW_GAME": ["New journey", "Nuevo viaje", "Nova jornada", "Nouveau voyage", "Neue Reise", "はじめから", "새 여정", "新的旅程"],
    "MENU_QUIT": ["Quit", "Salir", "Sair", "Quitter", "Beenden", "終了", "종료", "退出"],
    "MENU_OVERWRITE": ["Start a new journey? Your current progress will be lost.", "¿Empezar un nuevo viaje? Se perderá el progreso actual.", "Começar uma nova jornada? O progresso atual será perdido.", "Commencer un nouveau voyage ? La progression actuelle sera perdue.", "Neue Reise beginnen? Der aktuelle Fortschritt geht verloren.", "新しく始めますか？現在の進行状況は失われます。", "새 여정을 시작할까요? 현재 진행 상황이 사라집니다.", "开始新的旅程？当前进度将会丢失。"],
    "MENU_YES": ["Yes", "Sí", "Sim", "Oui", "Ja", "はい", "예", "是"],
    "MENU_NO": ["No", "No", "Não", "Non", "Nein", "いいえ", "아니요", "否"],
    # Actions
    "ACT_EQUIP": ["Equip", "Equipar", "Equipar", "Équiper", "Ausrüsten", "装備", "장착", "装备"],
    "ACT_UNEQUIP": ["Remove", "Quitar", "Remover", "Retirer", "Ablegen", "外す", "해제", "卸下"],
    "ACT_USE": ["Use", "Usar", "Usar", "Utiliser", "Benutzen", "使う", "사용", "使用"],
    "ACT_QUICK": ["Quick slot", "Acceso rápido", "Atalho", "Raccourci", "Schnellplatz", "ショートカット", "빠른 슬롯", "快捷栏"],
    "ACT_CRAFT": ["Craft", "Fabricar", "Criar", "Fabriquer", "Herstellen", "作る", "제작", "制作"],
    "ACT_COOK": ["Cook", "Cocinar", "Cozinhar", "Cuisiner", "Kochen", "料理する", "요리", "烹饪"],
    "ACT_SAVE": ["Save", "Guardar", "Salvar", "Sauvegarder", "Speichern", "セーブ", "저장", "保存"],
    "ACT_QUIT_TO_MENU": ["Title screen", "Menú principal", "Menu principal", "Écran titre", "Titelbild", "タイトルへ", "타이틀로", "返回标题"],
    # Categories & slots
    "CAT_WEAPON": ["Weapons", "Armas", "Armas", "Armes", "Waffen", "武器", "무기", "武器"],
    "CAT_ARMOR": ["Gear", "Equipo", "Equipamento", "Tenue", "Ausrüstung", "防具", "장비", "装备"],
    "CAT_MATERIAL": ["Materials", "Materiales", "Materiais", "Matériaux", "Material", "素材", "재료", "材料"],
    "CAT_FOOD": ["Food", "Comida", "Comida", "Nourriture", "Essen", "食べ物", "음식", "食物"],
    "CAT_TOOL": ["Tools", "Herramientas", "Ferramentas", "Outils", "Werkzeug", "道具", "도구", "工具"],
    "CAT_KEY": ["Special", "Especiales", "Especiais", "Spécial", "Besonderes", "大切なもの", "특별", "特殊"],
    "SLOT_WEAPON": ["Weapon", "Arma", "Arma", "Arme", "Waffe", "武器", "무기", "武器"],
    "SLOT_HEAD": ["Head", "Cabeza", "Cabeça", "Tête", "Kopf", "頭", "머리", "头部"],
    "SLOT_BODY": ["Body", "Cuerpo", "Corpo", "Corps", "Körper", "胴", "몸", "身体"],
    "SLOT_LEGS": ["Legs", "Piernas", "Pernas", "Jambes", "Beine", "脚", "다리", "腿部"],
    "SLOT_ACCESSORY": ["Charm", "Accesorio", "Acessório", "Accessoire", "Zubehör", "装飾", "장신구", "饰品"],
    "INV_EMPTY_HINT": ["Nothing here yet. Explore!", "Aún no hay nada. ¡Explora!", "Nada aqui ainda. Explore!", "Rien pour l'instant. Explorez !", "Noch nichts hier. Erkunde!", "まだ何もない。探検しよう！", "아직 아무것도 없어요. 탐험하세요!", "这里还空着。去探索吧！"],
    "INV_SELECT_HINT": ["Tap an item to see details.", "Toca un objeto para ver detalles.", "Toque um item para ver detalhes.", "Touchez un objet pour les détails.", "Tippe auf einen Gegenstand.", "アイテムをタップで詳細。", "아이템을 탭하면 상세 정보.", "点击物品查看详情。"],
    # Stats
    "STAT_HEALTH": ["Health", "Vida", "Vida", "Vie", "Leben", "体力", "체력", "生命"],
    "STAT_STAMINA": ["Stamina", "Aguante", "Vigor", "Endurance", "Ausdauer", "がんばり", "기력", "耐力"],
    "STAT_DEFENSE": ["Defense", "Defensa", "Defesa", "Défense", "Abwehr", "防御", "방어", "防御"],
    "STAT_ATTACK": ["Attack", "Ataque", "Ataque", "Attaque", "Angriff", "攻撃", "공격", "攻击"],
    "STAT_DAMAGE": ["Damage", "Daño", "Dano", "Dégâts", "Schaden", "威力", "피해", "伤害"],
    "STAT_SPEED": ["Speed", "Velocidad", "Velocidade", "Vitesse", "Tempo", "速さ", "속도", "速度"],
    "STAT_REACH": ["Reach", "Alcance", "Alcance", "Portée", "Reichweite", "間合い", "사거리", "攻击范围"],
    "STAT_DURABILITY": ["Durability", "Durabilidad", "Durabilidade", "Solidité", "Haltbarkeit", "耐久", "내구도", "耐久"],
    "STAT_POTENCY": ["Potency", "Potencia", "Potência", "Puissance", "Stärke", "効力", "효력", "效力"],
    "STAT_HEIRLOOM": ["Heirloom: never breaks, only blunts. Repair with a forge stone.", "Reliquia: nunca se rompe, solo se mella. Repárala con piedra de forja.", "Relíquia: nunca quebra, só perde o fio. Repare com pedra de forja.", "Relique : ne casse jamais, s'émousse. Se répare à la pierre de forge.", "Erbstück: bricht nie, wird nur stumpf. Mit Schmiedestein reparieren.", "形見：壊れず鈍るだけ。鍛冶石で修理。", "유물: 부서지지 않고 무뎌질 뿐. 대장간 돌로 수리.", "传家宝：不会损坏，只会变钝。用锻造石修复。"],
    "STAT_METAL": ["Metal: attracts lightning in storms.", "Metal: atrae rayos en tormentas.", "Metal: atrai raios em tempestades.", "Métal : attire la foudre par orage.", "Metall: zieht bei Gewitter Blitze an.", "金属：嵐で雷を呼ぶ。", "금속: 폭풍 때 번개를 끌어들임.", "金属：暴风雨中会引雷。"],
    "CHARGED_SPIN": ["Hold: spin attack", "Mantener: ataque giratorio", "Segurar: giro", "Maintenir : attaque tournoyante", "Halten: Wirbelangriff", "長押し：回転斬り", "길게: 회전 공격", "长按：回旋攻击"],
    "CHARGED_THRUST": ["Hold: lunging thrust", "Mantener: estocada", "Segurar: estocada", "Maintenir : estoc", "Halten: Sturmstoß", "長押し：突進突き", "길게: 돌진 찌르기", "长按：突刺"],
    "CHARGED_SLAM": ["Hold: ground slam (breaks rock)", "Mantener: golpe al suelo (rompe rocas)", "Segurar: golpe no chão (quebra rochas)", "Maintenir : frappe au sol (brise la roche)", "Halten: Bodenstoß (bricht Fels)", "長押し：叩きつけ（岩も砕く）", "길게: 내려찍기 (바위 파괴)", "长按：砸地（可击碎岩石）"],
    "CHARGED_BOLT": ["Hold: fire bolt", "Mantener: proyectil de fuego", "Segurar: projétil de fogo", "Maintenir : trait de feu", "Halten: Feuerbolzen", "長押し：火炎弾", "길게: 화염탄", "长按：火焰弹"],
    "ARMOR_COLD_RESIST": ["Keeps you warm", "Abriga del frío", "Protege do frio", "Protège du froid", "Hält warm", "寒さに強くなる", "추위에 강해짐", "御寒"],
    "ARMOR_HEAT_RESIST": ["Keeps you cool", "Protege del calor", "Protege do calor", "Protège de la chaleur", "Hält kühl", "暑さに強くなる", "더위에 강해짐", "防暑"],
    "ARMOR_CLIMB_SPEED": ["Faster climbing", "Escalada más rápida", "Escalada mais rápida", "Escalade plus rapide", "Schneller klettern", "登る速度アップ", "등반 속도 증가", "攀爬加速"],
    "ARMOR_STAMINA_REGEN": ["Faster stamina recovery", "Aguante se recupera antes", "Vigor recupera mais rápido", "Endurance plus rapide", "Schnellere Ausdauer", "がんばり回復アップ", "기력 회복 증가", "耐力恢复加快"],
    "ARMOR_LIGHTNING_IMMUNE": ["Grounds lightning", "Desvía los rayos", "Desvia raios", "Détourne la foudre", "Leitet Blitze ab", "雷を逃がす", "번개를 흘려보냄", "引开雷电"],
    "ARMOR_SPEED": ["Faster movement", "Movimiento más rápido", "Movimento mais rápido", "Déplacement plus rapide", "Schnellere Bewegung", "移動速度アップ", "이동 속도 증가", "移动加速"],
    "SET_TRAVELER": ["Traveler set (3): faster stamina recovery", "Conjunto viajero (3): recuperas aguante antes", "Conjunto viajante (3): vigor recupera mais rápido", "Tenue du voyageur (3) : endurance plus rapide", "Reiseset (3): schnellere Ausdauer", "旅人セット(3)：がんばり回復アップ", "여행자 세트(3): 기력 회복 증가", "旅人套装(3)：耐力恢复加快"],
    "CRAFT_NEEDS_CAMPFIRE": ["Needs a campfire", "Requiere fogata", "Requer fogueira", "Feu de camp requis", "Braucht Lagerfeuer", "焚き火が必要", "모닥불 필요", "需要篝火"],
    # Status
    "STATUS_FREEZING": ["Freezing!", "¡Congelándote!", "Congelando!", "Gelé !", "Frierst!", "凍えている！", "얼어붙는 중!", "寒冷！"],
    "STATUS_HOT": ["Overheating!", "¡Demasiado calor!", "Superaquecendo!", "Surchauffe !", "Überhitzt!", "暑すぎる！", "과열!", "过热！"],
    "STATUS_BURNING": ["Burning", "Ardiendo", "Queimando", "En feu", "Brennt", "炎上", "화상", "燃烧"],
    "STATUS_WET": ["Wet", "Mojado", "Molhado", "Mouillé", "Nass", "濡れ", "젖음", "潮湿"],
    "STATUS_SHOCKED": ["Shocked", "Electrocutado", "Eletrocutado", "Électrocuté", "Geschockt", "感電", "감전", "触电"],
    "STATUS_CHILLED": ["Chilled", "Helado", "Gelado", "Transi", "Unterkühlt", "冷え", "냉기", "冰冷"],
    "STATUS_METAL_STORM": ["Metal in a storm!", "¡Metal en la tormenta!", "Metal na tempestade!", "Métal sous l'orage !", "Metall im Gewitter!", "嵐に金属！", "폭풍 속 금속!", "雷雨中携带金属！"],
    # Buffs
    "BUFF_COLD_RESIST": ["Warm", "Abrigo", "Aquecido", "Chaleur", "Wärme", "暖か", "온기", "保暖"],
    "BUFF_HEAT_RESIST": ["Cool", "Frescor", "Refresco", "Fraîcheur", "Kühle", "ひんやり", "냉기 보호", "清凉"],
    "BUFF_ATTACK_UP": ["Fierce", "Fiereza", "Fúria", "Férocité", "Wildheit", "攻撃アップ", "공격 강화", "攻击提升"],
    "BUFF_DEFENSE_UP": ["Stout", "Robustez", "Robustez", "Robustesse", "Zähigkeit", "防御アップ", "방어 강화", "防御提升"],
    "BUFF_SPEED_UP": ["Swift", "Presteza", "Ligeireza", "Célérité", "Flinkheit", "移動アップ", "신속", "迅捷"],
    "BUFF_REGEN": ["Mending", "Regeneración", "Regeneração", "Régénération", "Heilung", "回復", "재생", "再生"],
    "BUFF_STAMINA_REGEN": ["Vigor", "Vigor", "Vigor", "Vigueur", "Elan", "活力", "활력", "活力"],
    # Weather
    "WEATHER_CLEAR": ["Clear", "Despejado", "Limpo", "Dégagé", "Klar", "晴れ", "맑음", "晴"],
    "WEATHER_CLOUDY": ["Cloudy", "Nublado", "Nublado", "Nuageux", "Bewölkt", "くもり", "흐림", "多云"],
    "WEATHER_RAIN": ["Rain", "Lluvia", "Chuva", "Pluie", "Regen", "雨", "비", "雨"],
    "WEATHER_STORM": ["Storm", "Tormenta", "Tempestade", "Orage", "Gewitter", "嵐", "폭풍", "雷雨"],
    "WEATHER_FOG": ["Fog", "Niebla", "Neblina", "Brouillard", "Nebel", "霧", "안개", "雾"],
    "WEATHER_WINDY": ["Windy", "Ventoso", "Ventania", "Venteux", "Windig", "強風", "강풍", "大风"],
    "WEATHER_SNOW": ["Snow", "Nieve", "Neve", "Neige", "Schnee", "雪", "눈", "雪"],
    # Toasts
    "TOAST_WELCOME": ["Heath Hamlet", "Aldea del Brezo", "Aldeia da Urze", "Hameau de la Lande", "Heideweiler", "ヒースの村", "히스 마을", "石楠村"],
    "TOAST_DISCOVERED": ["Discovered: %s", "Descubierto: %s", "Descoberto: %s", "Découvert : %s", "Entdeckt: %s", "発見：%s", "발견: %s", "发现：%s"],
    "TOAST_SAVED": ["Progress saved", "Progreso guardado", "Progresso salvo", "Progression sauvegardée", "Fortschritt gespeichert", "セーブしました", "저장됨", "进度已保存"],
    "TOAST_INVENTORY_FULL": ["No room for that", "No hay espacio", "Sem espaço", "Plus de place", "Kein Platz", "持ちきれない", "공간이 부족함", "背包已满"],
    "TOAST_WEAPON_WORN": ["%s is about to break", "%s está a punto de romperse", "%s está prestes a quebrar", "%s va bientôt casser", "%s zerbricht bald", "%sが壊れそう", "%s이(가) 곧 부서짐", "%s快要损坏了"],
    "TOAST_WEAPON_BROKE": ["%s broke!", "¡%s se rompió!", "%s quebrou!", "%s s'est brisé !", "%s ist zerbrochen!", "%sが壊れた！", "%s이(가) 부서졌다!", "%s损坏了！"],
    "TOAST_LIGHTNING_WARNING": ["Your metal gear is crackling… lightning is coming!", "Tu equipo de metal chisporrotea… ¡viene un rayo!", "Seu equipamento de metal estala… um raio vem aí!", "Votre métal crépite… la foudre arrive !", "Dein Metall knistert … ein Blitz kommt!", "金属がパチパチ…雷が来る！", "금속 장비가 지직거린다… 번개가 온다!", "金属装备噼啪作响……雷要来了！"],
    "TOAST_GUARD_BROKEN": ["Guard broken!", "¡Guardia rota!", "Guarda quebrada!", "Garde brisée !", "Deckung gebrochen!", "ガードが崩れた！", "방어가 무너졌다!", "防御被破！"],
    "TOAST_EXHAUSTED_WATER": ["Too tired to swim…", "Demasiado cansado para nadar…", "Cansado demais para nadar…", "Trop épuisé pour nager…", "Zu erschöpft zum Schwimmen …", "泳ぐ力が尽きた…", "헤엄칠 힘이 없다…", "累得游不动了……"],
    "TOAST_NONE_LEFT": ["No %s left", "No te queda %s", "Sem %s", "Plus de %s", "Kein %s mehr", "%sがない", "%s 없음", "没有%s了"],
    "TOAST_NOTHING_TO_REPAIR": ["Your weapon doesn't need repair", "Tu arma no necesita reparación", "Sua arma não precisa de reparo", "Votre arme n'a pas besoin de réparation", "Deine Waffe braucht keine Reparatur", "修理の必要はない", "수리가 필요 없음", "武器无需修理"],
    "TOAST_NEEDS_INGOT": ["Heirlooms need a forge stone", "Las reliquias requieren piedra de forja", "Relíquias exigem pedra de forja", "Les reliques exigent une pierre de forge", "Erbstücke brauchen einen Schmiedestein", "形見には鍛冶石が必要", "유물은 대장간 돌이 필요함", "传家宝需要锻造石"],
    "TOAST_REPAIRED": ["Weapon repaired", "Arma reparada", "Arma reparada", "Arme réparée", "Waffe repariert", "修理した", "무기 수리 완료", "武器已修复"],
    "TOAST_COOKED": ["Cooked: %s", "Cocinado: %s", "Cozido: %s", "Cuisiné : %s", "Gekocht: %s", "完成：%s", "완성: %s", "做好了：%s"],
    "TOAST_RESTED": ["You feel rested", "Te sientes descansado", "Você se sente descansado", "Vous êtes reposé", "Du bist ausgeruht", "よく休んだ", "푹 쉬었다", "休息好了"],
    "TOAST_MAX_HEALTH": ["Your heart grows stronger", "Tu corazón se fortalece", "Seu coração se fortalece", "Votre cœur se renforce", "Dein Herz wird stärker", "体力の上限が増えた", "최대 체력 증가", "生命上限提升"],
    "TOAST_MAX_STAMINA": ["Your breath runs deeper", "Tu aliento es más profundo", "Seu fôlego se aprofunda", "Votre souffle s'allonge", "Dein Atem wird tiefer", "がんばりの上限が増えた", "최대 기력 증가", "耐力上限提升"],
    # Camp
    "CAMP_TITLE": ["Campfire", "Fogata", "Fogueira", "Feu de camp", "Lagerfeuer", "焚き火", "모닥불", "篝火"],
    "CAMP_HINT": ["Pick up to 5 ingredients. Unknown combinations show ???", "Elige hasta 5 ingredientes. Las combinaciones nuevas muestran ???", "Escolha até 5 ingredientes. Combinações novas mostram ???", "Choisissez jusqu'à 5 ingrédients. Les combinaisons inconnues affichent ???", "Bis zu 5 Zutaten wählen. Unbekannte Kombinationen: ???", "材料を5つまで選ぶ。未知の組み合わせは ???", "재료를 최대 5개 선택. 새 조합은 ???", "最多选择5种食材。未知组合显示 ???"],
    "CAMP_REST_MORNING": ["Rest till morning", "Descansar hasta la mañana", "Descansar até de manhã", "Dormir jusqu'au matin", "Bis morgens ruhen", "朝まで休む", "아침까지 휴식", "休息到早晨"],
    "CAMP_REST_NOON": ["Rest till noon", "Descansar hasta mediodía", "Descansar até meio-dia", "Dormir jusqu'à midi", "Bis mittags ruhen", "昼まで休む", "정오까지 휴식", "休息到中午"],
    "CAMP_REST_NIGHT": ["Rest till night", "Descansar hasta la noche", "Descansar até a noite", "Dormir jusqu'au soir", "Bis nachts ruhen", "夜まで休む", "밤까지 휴식", "休息到夜晚"],
    # Settings
    "SET_AUDIO": ["Audio", "Audio", "Áudio", "Audio", "Audio", "サウンド", "오디오", "音频"],
    "SET_MUSIC": ["Music", "Música", "Música", "Musique", "Musik", "音楽", "음악", "音乐"],
    "SET_SFX": ["Effects", "Efectos", "Efeitos", "Effets", "Effekte", "効果音", "효과음", "音效"],
    "SET_AMBIENCE": ["Ambience", "Ambiente", "Ambiente", "Ambiance", "Umgebung", "環境音", "환경음", "环境音"],
    "SET_CONTROLS": ["Controls & camera", "Controles y cámara", "Controles e câmera", "Commandes et caméra", "Steuerung & Kamera", "操作とカメラ", "조작 및 카메라", "操作与镜头"],
    "SET_CAMERA_SENS": ["Camera sensitivity", "Sensibilidad de cámara", "Sensibilidade da câmera", "Sensibilité caméra", "Kameraempfindlichkeit", "カメラ感度", "카메라 감도", "镜头灵敏度"],
    "SET_INVERT_Y": ["Invert vertical", "Invertir vertical", "Inverter vertical", "Inverser l'axe vertical", "Vertikal invertieren", "上下反転", "상하 반전", "垂直反转"],
    "SET_AUTO_CAMERA": ["Auto camera", "Cámara automática", "Câmera automática", "Caméra auto", "Auto-Kamera", "オートカメラ", "자동 카메라", "自动镜头"],
    "SET_CONTROLS_SIZE": ["Button size", "Tamaño de botones", "Tamanho dos botões", "Taille des boutons", "Tastengröße", "ボタンの大きさ", "버튼 크기", "按钮大小"],
    "SET_CONTROLS_OPACITY": ["Button opacity", "Opacidad de botones", "Opacidade dos botões", "Opacité des boutons", "Tastendeckkraft", "ボタンの不透明度", "버튼 불투명도", "按钮透明度"],
    "SET_LEFT_HANDED": ["Left-handed layout", "Diseño para zurdos", "Layout canhoto", "Disposition gaucher", "Linkshänder-Layout", "左利き配置", "왼손잡이 배치", "左手布局"],
    "SET_VIBRATION": ["Vibration", "Vibración", "Vibração", "Vibration", "Vibration", "振動", "진동", "振动"],
    "SET_GRAPHICS": ["Graphics & performance", "Gráficos y rendimiento", "Gráficos e desempenho", "Graphismes et performances", "Grafik & Leistung", "グラフィックと性能", "그래픽 및 성능", "画面与性能"],
    "SET_QUALITY": ["Quality", "Calidad", "Qualidade", "Qualité", "Qualität", "画質", "품질", "画质"],
    "SET_Q_AUTO": ["Auto", "Automática", "Automática", "Auto", "Auto", "自動", "자동", "自动"],
    "SET_Q_LOW": ["Low", "Baja", "Baixa", "Basse", "Niedrig", "低", "낮음", "低"],
    "SET_Q_MEDIUM": ["Medium", "Media", "Média", "Moyenne", "Mittel", "中", "중간", "中"],
    "SET_Q_HIGH": ["High", "Alta", "Alta", "Haute", "Hoch", "高", "높음", "高"],
    "SET_Q_ULTRA": ["Ultra", "Ultra", "Ultra", "Ultra", "Ultra", "最高", "최상", "极高"],
    "SET_FPS": ["Frame rate", "FPS", "FPS", "Images/s", "Bildrate", "フレームレート", "프레임", "帧率"],
    "SET_DYNAMIC_RES": ["Dynamic resolution", "Resolución dinámica", "Resolução dinâmica", "Résolution dynamique", "Dynamische Auflösung", "動的解像度", "동적 해상도", "动态分辨率"],
    "SET_BATTERY": ["Battery saver (30 FPS)", "Ahorro de batería (30 FPS)", "Economia de bateria (30 FPS)", "Économie de batterie (30 i/s)", "Akkusparmodus (30 FPS)", "省電力（30FPS）", "배터리 절약 (30FPS)", "省电模式（30帧）"],
    "SET_SHOW_FPS": ["Show FPS", "Mostrar FPS", "Mostrar FPS", "Afficher les i/s", "FPS anzeigen", "FPS表示", "FPS 표시", "显示帧率"],
    "SET_ACCESSIBILITY": ["Accessibility & language", "Accesibilidad e idioma", "Acessibilidade e idioma", "Accessibilité et langue", "Barrierefreiheit & Sprache", "アクセシビリティと言語", "접근성 및 언어", "辅助功能与语言"],
    "SET_TEXT_SIZE": ["Text size", "Tamaño de texto", "Tamanho do texto", "Taille du texte", "Textgröße", "文字サイズ", "글자 크기", "文字大小"],
    "SET_SUBTITLES": ["Subtitles", "Subtítulos", "Legendas", "Sous-titres", "Untertitel", "字幕", "자막", "字幕"],
    "SET_LANGUAGE": ["Language", "Idioma", "Idioma", "Langue", "Sprache", "言語", "언어", "语言"],
    "SET_LANG_AUTO": ["Device language", "Idioma del dispositivo", "Idioma do dispositivo", "Langue de l'appareil", "Gerätesprache", "端末の言語", "기기 언어", "设备语言"],
    "SET_PRIVACY": ["Privacy", "Privacidad", "Privacidade", "Confidentialité", "Datenschutz", "プライバシー", "개인정보", "隐私"],
    "SET_ANALYTICS": ["Share anonymous usage data", "Compartir datos de uso anónimos", "Compartilhar dados anônimos", "Partager des données anonymes", "Anonyme Nutzungsdaten teilen", "匿名の利用データを送信", "익명 사용 데이터 공유", "共享匿名使用数据"],
    "SET_GAME": ["Game", "Partida", "Jogo", "Partie", "Spiel", "ゲーム", "게임", "游戏"],
    "LANG_EN": ["English", "English", "English", "English", "English", "English", "English", "English"],
    "LANG_ES": ["Español", "Español", "Español", "Español", "Español", "Español", "Español", "Español"],
    "LANG_PT": ["Português", "Português", "Português", "Português", "Português", "Português", "Português", "Português"],
    "LANG_FR": ["Français", "Français", "Français", "Français", "Français", "Français", "Français", "Français"],
    "LANG_DE": ["Deutsch", "Deutsch", "Deutsch", "Deutsch", "Deutsch", "Deutsch", "Deutsch", "Deutsch"],
    "LANG_JA": ["日本語", "日本語", "日本語", "日本語", "日本語", "日本語", "日本語", "日本語"],
    "LANG_KO": ["한국어", "한국어", "한국어", "한국어", "한국어", "한국어", "한국어", "한국어"],
    "LANG_ZH": ["中文", "中文", "中文", "中文", "中文", "中文", "中文", "中文"],
    # Loading, dialogue, map
    "LOADING_WORLD": ["Unfolding the map…", "Desplegando el mapa…", "Abrindo o mapa…", "Dépliage de la carte…", "Karte wird entfaltet …", "地図を広げています…", "지도를 펼치는 중…", "正在展开地图……"],
    "LOADING_TERRAIN": ["Raising the land…", "Levantando la tierra…", "Erguendo a terra…", "Le relief se dessine…", "Das Land erhebt sich …", "大地を形作っています…", "대지를 빚는 중…", "大地正在成形……"],
    "LOADING_READY": ["Ready", "Listo", "Pronto", "Prêt", "Bereit", "準備完了", "준비 완료", "准备就绪"],
    "DIALOGUE_TAP": ["Tap to continue", "Toca para continuar", "Toque para continuar", "Touchez pour continuer", "Tippen zum Fortfahren", "タップで次へ", "탭하여 계속", "点击继续"],
    "MAP_HINT": ["Tap to place a pin", "Toca para poner un marcador", "Toque para marcar", "Touchez pour placer un repère", "Tippen für Markierung", "タップでピンを置く", "탭하여 핀 놓기", "点击放置标记"],
}
